using System;

namespace Sdo.Game
{
    /// <summary>
    /// SCN0003 (車庫 disco floor) per-tile animation table — decompiled DAT_0054fdb0 (Scene_UpdateSceneObjects case 3,
    /// 030_scene_004b43c0.c:3557). The 256 floor tiles do NOT pulse in lockstep: every 300 ms the engine advances a
    /// pattern STEP (0..22, %0x17) and sets each tile's texture to BOX_&lt;Table[step*256 + tile]&gt; (frame 0..5). The
    /// 23 steps form a moving formation (arrows / letters) sweeping across the grid. Tile index = the box instance
    /// order in SceneMapobjCatalog (the diamond-grid expansion). Driven by BoxFloorAnimator.
    /// </summary>
    public static class BoxFloorPattern
    {
        public const int Steps = 23;
        public const int Tiles = 256;
        public const float IntervalMs = 300f;

        public static readonly byte[] Table = Convert.FromBase64String(
            "AAABAQABAQUFAAAAAQEBAQAAAQEAAQEFBQAAAAEBAQEAAAEBAAEBBQUBAQEAAAAAAAABAQABAQQDAAAAAQEBAQEAAAABAAAEAwAAAAEBAQEBAAAAAQAABAMA" +
            "AAAAAAAAAQAAAAEAAAUFAQEBAAAAAAUFBQQEBAMFAwUDAwMFBQUFBQUDAwMFAwUDBAQEBQUFAAABAQABAQUFAAAAAQEBAQAAAQEAAQEDBAAAAAEBAQEAAAEB" +
            "AAEBAwQBAQEAAAAAAAABAQABAQMEAAAAAQEBAQEAAAABAAAFBQAAAAEBAQEBAAAAAQAABQUAAAAAAAAAAQAAAAEAAAUFAQEBAAAAAAABAAEBAQEBAQEBAQEA" +
            "AAAAAQABAQEBAQAAAAABAQEBAQECBQUFBQUCAgICAgMAAAABAwICAgICAgICAgUFAAAAAQMCAgICAgIFBQUFBQAAAAEFBQUDBAQFBAUDAwIBAQEAAgIEBAUE" +
            "BQQEAgICAQEBAAUDBQQDBAQDBAQEAwEBAQAFBAQFAgICAgUFAwUBAQABBQMFAgICAgUDBAQCAAAAAQIEBAUEAwQEBQIFAwEBAQAFAwQEBAQEAwQFBQIBAQEA" +
            "AwICBQQCAgIFBQUCAAABAQQDAgUFBQIFAgICBQAAAQEBAQEBAQAAAAEAAAEBAQAAAAEBAQAAAAEBAQABAQEAAAABAQEBAQEBAQEBAAAAAAAAAgEBAQEAAAAB" +
            "AQEBAQEBBAIEAAABAQEBAQEAAAAAAgUEAgIAAQEBAQEBAAAAAAAFAgMFAwEAAAEBAQEAAAAAAAQCBQQEAAAAAQEBAQEBAQEBBQUFBAIAAAEBAQEBAAABAQEC" +
            "BQMBAwABAQEBAQEBAQEAAAMEAgQCAQAAAAAAAAABAAABAgIDAgMBAQEBAQEBAQABAQECBQUEBAEBAQEBAQEAAQEBAQUCBAQEAQEBAQEBAQEBAQEBBAUCAwIB" +
            "AAABAQEBAAAAAQEFAgQAAAAAAAEBAQAAAAEBAQIAAAABAQEBAAAAAQEBAQEAAQEBAgIAAQEBAQEBAQEBAQAAAAICAAEBAQEBAAAAAAEBAQEEBQAAAQEBAQEB" +
            "AQEBAAAABAUAAAEBAQEBAQEBAQAAAAQFAQEBAQEAAAAAAAAAAAAEBQEBAAAAAQEBAQEBAQEBBQUBAQAAAAEBAQEBAQEBAQUDAQEBAQEBAQEAAAABAQEFAwAA" +
            "AQEBAQEBAAAAAQEBBQQAAAEBAQEBAQEBAQAAAAMEAQEBAQEBAQEAAAABAQEFAwEBAAAAAQEBAAAAAQEBBAUBAQEBAQEBAQEBAQAAAAUFAAAAAAEBAQEBAQEA" +
            "AAADAwUFAwQEAwMFBQUFBQICBAMFBAUDBQUFBQQEBAQCAgACAgEBAQEBAQEBAQEAAAAAAgIBAQEBAQAAAAABAQEBAQQFAAEBAQEBAQEBAQAAAAAEBQABAQEB" +
            "AQEBAQEAAAAABAUBAQEBAAAAAAAAAAAAAAQFAQAAAAEBAQEBAQEBAQEFBQEAAAABAQEBAQEBAQEBBQMBAQEBAQEBAAAAAQEBAQUDAAEBAQEBAQAAAAEBAQAF" +
            "BAABAQEBAQEBAQEAAAAAAwQBAQEBAQEBAAAAAQEBAQUDAQAAAAEBAQAAAAEBAQEEBQEBAQEBAQEBAQEAAAADBQUFAwQEAwMFBQUFBQICBAMFBAUDBQUFBQQE" +
            "BAQCAgADBQEBAQAAAAEBAQABAQEAAQICAQEBAQEBAQEBAAAAAAECAgEBAQEAAAAAAQEBAQEBBAUBAQEBAQEBAQEAAAAAAQQFAQEBAQEBAQEBAAAAAAEEBQEB" +
            "AQAAAAAAAAAAAAABBAUAAAABAQEBAQEBAQEBAAUFAAAAAQEBAQEBAQEBAQAFAwEBAQEBAQAAAAEBAQEABQMBAQEBAQEAAAABAQEAAQUEAQEBAQEBAQEBAAAA" +
            "AAEDBAEBAQEBAQAAAAEBAQEABQMAAAABAQEAAAABAQEDBAUFAwQEAwMFBQUFBQICBAUFBAUDBQUFBQQEBAQCAgEBAwUBAQEAAAABAAABAQEAAAMFAQEAAAAB" +
            "AQEAAQEBAAEAAgIBAQEBAQEBAQAAAAABAAICAQEBAAAAAAEBAQEBAQAEBQEBAQEBAQEBAAAAAAEABAUBAQEBAQEBAQAAAAABAQQFAQEAAAAAAAAAAAAAAQEE" +
            "BQAAAQEBAQEBAQEBAQABBQUAAAEBAQEBAQEBAQEAAQUDAQEBAQEAAAABAQEBAAAFAwEBAQEBAAAAAQEBAAEABQQBAQEBAQEBAQAAAAABAQMEAQEBAQEAAAAB" +
            "AQEDBQUFAwQEAwMFBQUFBQICBAMFBAUDBQUFBQQEBAQCAgEBAAUDAAEBAQEBAQAAAAABAQEEBQEBAAAAAQAAAQEBAAAAAwUBAAAAAQEBAAEBAQABAAECAgEB" +
            "AQEBAQEAAAAAAQABAgIBAQAAAAABAQEBAQEAAAQFAQEBAQEBAQAAAAABAAAEBQEBAQEBAQEAAAAAAQEBBAUBAAAAAAAAAAAAAAEBAQQFAAEBAQEBAQEBAQEA" +
            "AQEFBQABAQEBAQEBAQEBAAEBBQMBAQEBAAAAAQEBAQAAAAUDAQEBAQAAAAEBAQABAAAFBAEBAQEBAQEAAAADBQUFAwQEAwMFBQUFBQICBAMFBAMEBQUFBQQE" +
            "BAQCAgEAAQEFAwEBAQEBAQEAAAABAQAABQMBAQEBAQEAAAAAAQEBAQQFAQAAAAEAAAEBAQAAAAEDBQAAAAEBAQABAQEAAQABAQICAQEBAQEBAAAAAAEAAQEC" +
            "AgEAAAAAAQEBAQEBAAABBAUBAQEBAQEAAAAAAQAAAQQFAQEBAQEBAAAAAAEBAQEEBQAAAAAAAAAAAAABAQEABAUBAQEBAQEBAQEBAAEBAAUFAQEBAQEBAQEB" +
            "AQABAQEFAwEBAQAAAAEBAQEAAAABBQMBAQEAAAABAQEDBQUFAwUEAwMFBQUFBQICBAMFBAMEBAUFBQQEBAQCAgEAAQEABAUBAQEAAAABAQEBAAEBAQUDAQEB" +
            "AQEBAAAAAQEAAAAFAwEBAQEBAAAAAAEBAQEBBAUAAAABAAABAQEAAAABAQMFAAABAQEAAQEBAAEAAQEBAgIBAQEBAQAAAAABAAEBAQICAAAAAAEBAQEBAQAA" +
            "AQEEBQEBAQEBAAAAAAEAAAEBBAUBAQEBAQAAAAABAQEBAQQFAAAAAAAAAAAAAQEBAAAEBQEBAQEBAQEBAQABAQAABQUBAQEBAQEBAQEAAQEBAQUDAQEAAAAB" +
            "AQEDBQUFAwUFAwMFBQUFBQICBAMFBAMEBAMFBQQEBAQCAgABAQEBAQQFAQEAAAABAQEBAAEBAAAEBQEBAAAAAQEBAQABAQEBBQMBAQEBAQAAAAEBAAAAAAUD" +
            "AQEBAQAAAAABAQEBAQEEBQAAAQAAAQEBAAAAAQEBAwUAAQEBAAEBAQABAAEBAQEBAgIBAQEAAAAAAQABAQEBAQICAAABAQEBAQEAAAEBAQEEBQEBAQAAAAAB" +
            "AAABAQEBBAUBAQEAAAAAAQEBAQEBAAQFAAAAAAAAAAEBAQAAAAEEBQEBAQEBAQMFBQUDBQUDBQUFBQUFAgIEAwUEAwQEAwUDBAQEBAICAQAAAAEBAQEDBQAA" +
            "AAEBAQABAAABAQEBBQUBAQEAAAAAAQEBAQEBAQQFAAAAAQEBAQABAQAAAAEEBQAAAAEBAQEAAQEBAQEBBQMBAQEAAAABAQAAAAABAQUDAQEAAAAAAQEBAQEB" +
            "AQAEBQEAAAEBAQAAAAEBAQAAAwUBAQABAQEAAQABAQEBAQECAgEBAAAAAAEAAQEBAQEAAgIAAQEBAQEBAAABAQEBAQQFAQEAAAAAAQAAAQEBAQEEBQEBAAAA" +
            "AAEBAQEBAQAABAUAAAAAAAMFBQUDBQUDBQQFBQUFAgIEAwUEAwQEAwUFBQQEBAICAQABAQEBAQEBAwQAAAEBAQEAAAABAQEBAQMFAAABAQEAAQAAAQEBAQEF" +
            "BQEBAAAAAAEBAQEBAQEBBAUAAAEBAQEAAQEAAAABAQQFAAABAQEBAAEBAQEBAQEFAwEBAAAAAQEAAAAAAQEBBQMBAAAAAAEBAQEBAQEAAAQFAAABAQEAAAAB" +
            "AQEAAAADBQEAAQEBAAEAAQEBAQEBAQICAQAAAAABAAEBAQEBAAACAgEBAQEBAQAAAQEBAQEBBAUBAAAAAAEAAAEBAQEBAQQFAQAAAAMFBQUDBQUDBQQEBQUF" +
            "AgIEAwUEAwQEAwUFBQUEBAICAQABAQAAAAEBAQUEAQEBAQEAAQEBAQEBAQEDBAABAQEBAAAAAQEBAQEBAwUAAQEBAAEAAAEBAQEBAQUFAQAAAAABAQEBAQEB" +
            "AQEEBQABAQEBAAEBAAAAAQEBBAUAAQEBAQABAQEBAQEBAQUDAQAAAAEBAAAAAAEBAQEFAwAAAAABAQEBAQEBAAAABAUAAQEBAAAAAQEBAAAAAQMFAAEBAQAB" +
            "AAEBAQEBAQEBAgIAAAAAAQABAQEBAQAAAAICAQEBAQEAAAEBAQEBAQEEBQAAAAMFBQUDBQUDBQQEBAUFAgIEAwUEAwQEAwUFBQUFBAICAAEBAQAAAAEBAQEF" +
            "BAEBAQEAAQEAAAABAQEBBQQBAQEBAAEBAQEBAQEBAAMEAQEBAQAAAAEBAQEBAQADBQEBAQABAAABAQEBAQEBBQUAAAAAAQEBAQEBAQEBAAQFAQEBAQABAQAA" +
            "AAEBAQAEBQEBAQEAAQEBAQEBAQEBBQMAAAABAQAAAAABAQEBAQUDAAAAAQEBAQEBAQAAAAEEBQEBAQAAAAEBAQAAAAEBAwUBAQEAAQABAQEBAQEBAQECAgAA" +
            "AAEAAQEBAQEAAAAAAgIBAQMFBQUDBQUDBQQEBAQFAgIEAwUEAwQEAwUFBQUFBQICAAEBAQEBAQAAAAAABQQAAAABAQEAAAABAQEBAQUEAQEBAAEBAAAAAQEB" +
            "AQEFBAEBAQABAQEBAQEBAQAAAwQBAQEAAAABAQEBAQEAAAMFAQEAAQAAAQEBAQEBAQEFBQAAAAEBAQEBAQEBAQAABAUBAQEAAQEAAAABAQEAAAQFAQEBAAEB" +
            "AQEBAQEBAQEFAwAAAQEAAAAAAQEBAQEBBQMAAAEBAQEBAQEAAAABAAQFAQEAAAABAQEAAAABAQEDBQEBAAEAAQEBAQEBAQEBAQICAAMFBQUDBQUDBQQEBAIC" +
            "AgIEAwUEAwQEAwUFBQUEBQICAAEAAAEBAQEBAQEBAQUFAAABAQEBAQEAAAAAAAAFBAAAAQEBAAAAAQEBAQEBBQQBAQABAQAAAAEBAQEBAQUEAQEAAQEBAQEB" +
            "AQEAAAADBAEBAAAAAQEBAQEBAAAAAwUBAAEAAAEBAQEBAQEBAQUFAAABAQEBAQEBAQEAAAAEBQEBAAEBAAAAAQEBAAAABAUBAQABAQEBAQEBAQEBAQUDAAEB" +
            "AAAAAAEBAQEBAQAFAwABAQEBAQEBAAAAAQAABAUBAAAAAQEBAAAAAQEBAAMFAQMFBQUDBQUDBQQEBAICAgIEAwUEAwQEAwUFBQUEAgICAQEAAAEBAQEBAQEB" +
            "AQAFAgABAAABAQEBAQEBAQEABQUAAQEBAQEBAAAAAAAAAAUEAAEBAQAAAAEBAQEBAQEFBAEAAQEAAAABAQEBAQEBBQQBAAEBAQEBAQEBAAAAAQMEAQAAAAEB" +
            "AQEBAQAAAAEDBQABAAABAQEBAQEBAQEABQUAAQEBAQEBAQEBAAAAAQQFAQABAQAAAAEBAQAAAAEEBQEAAQEBAQEBAQEBAQEABQMBAQAAAAABAQEBAQEAAAUD" +
            "AQEBAQEBAQAAAAEAAAEEBQAAAAEBAQAAAAEBAQABAwUAAQABAQEBAQEBAQEBAAAAAAEAAQEBAQEAAAAAAQEBAQEBAAABAQEBAQEBAQEAAAAAAQACAgICAgIC" +
            "AgIFAAAAAAEBAgICAgICBQUFBQAAAAABAQUFAwQEBQQFAwMBAQEBAAECBAQFBAUEBAICAQEBAQABAwUEAwQEAwQEBAEBAQEAAAQEBQICAgIFBQMBAQEAAQAD" +
            "BQICAgIFAwQEAAAAAAEBBAQFBAMEBAUCBQEBAQEAAQMEBAQEBAMEBQUBAQEBAAECAgUEAgICBQUFAAAAAQEAAAAAAQEBAQEBAAAAAAEBAQEBAQEAAAABAAAB" +
            "AQEAAAABAQEAAAABAQEAAQEBAAEAAQEBAQEBAQEBAQAAAAABAAEBAQEBAAAAAAEBAQEBAQAAAQEBAQEBAQEBAAAAAAEAAAEBAQEBAQEBAQAAAAABAQECAgIC" +
            "AgUFBQAAAAAAAQEBBQMEBAUEBQMBAQEBAQABAQQEBQQFBAQCAQEBAQEAAQEFBAMEBAMEBAABAQEBAAAABAUCAgICBQUAAQEBAAEAAAUCAgICBQMEAQAAAAAB" +
            "AQEEBQQDBAQFAgABAQEBAAEBBAQEBAQDBAUAAQEBAQABAQEBAQEBAQEBAQAAAAEBAAAAAAEBAQEBAQAAAAABAQEBAQEBAAAAAQAAAQEBAAAAAQEBAAAAAQEB" +
            "AAEBAQABAAEBAQEBAQEBAQEAAAAAAQABAQEBAQAAAAABAQEBAQEAAAEBAQEBAQEBAQAAAAABAAABAQEBAQEBAQEAAAAAAQEBAQEBAAAAAAAAAAAAAAEBAQAD" +
            "BAQFBAUBAQEBAQEAAQEABAUEBQQEAQEBAQEBAAEBAQQDBAQDBAAAAQEBAQAAAAEFAgICAgUAAAEBAQABAAABAgICAgUDAQEAAAAAAQEBAQUEAwQEBQAAAQEB" +
            "AQABAQAAAAEBAQAAAAEBAQEAAQEBAQEBAQEBAQEAAAABAQAAAAABAQEBAQEAAAAAAQEBAQEBAQAAAAEAAAEBAQAAAAEBAQAAAAEBAQABAQEAAQABAQEBAQEB" +
            "AQEBAAAAAAEAAQEBAQEAAAAAAQEBAQEBAAABAQEBAQEBAQEAAAAAAQAAAQEBAQEBAQEBAAAAAAEBAQEBAQAAAAAAAAAAAAABAQEAAAABAQEBAQEBAQEBAAEB" +
            "AAAFBAUEAQEBAQEBAQABAQEBAwQEAwAAAAEBAQEAAAABAQICAgIAAAABAQEAAQAAAQECAgIFAQEBAAAAAAEBAQEBAQEBAQAAAAEBAQEAAQEAAAABAQEAAAAB" +
            "AQEBAAEBAQEBAQEBAQEBAAAAAQEAAAAAAQEBAQEBAQAAAAEBAQEBAQEAAAABAAABAQEAAAABAQEAAAABAQEAAQEBAAEAAQEBAQEBAQEBAQAAAAABAAEBAQEB" +
            "AAAAAAEBAQEBAQAAAQEBAQEBAQEBAAAAAAEAAAEBAQEBAQEBAQAAAAABAQEBAQEAAAAAAAAAAAAAAQEBAAAAAQEBAQEBAQEBAQABAQAAAAEBAQEBAQEBAQEA" +
            "AQEBAQEEBAEAAAABAQEBAAAAAQEBAgIBAAAAAQEBAAEAAAEBAQEBAQEBAQAAAAABAQEBAQEBAQEAAAABAQEBAAEBAAAAAQEBAAAAAQEBAQABAQEBAQEBAQEB" +
            "AQAAAAEBAAAAAAEBAQEBAQAAAAABAQEBAQEBAAAAAQAAAQEBAAAAAQEBAAAAAQEBAAEBAQABAAEBAQEBAQEBAQEAAAAAAQABAQEBAQAAAAABAQEBAQEAAAEB" +
            "AQEBAQEBAQAAAAABAAABAQEBAQEBAQEAAAAAAQEBAQEBAAAAAAAAAAAAAAEBAQAAAAEBAQEBAQEBAQEAAQEAAAABAQEBAQEBAQEBAAEBAQEBAQEBAAAAAQEB" +
            "AQAAAAEBAQEBAQAAAAEBAQABAAABAQEBAQEBAQEAAAAAAQEBAQEBAQEBAAAAAQEBAQABAQAAAAEBAQAAAAEBAQEAAQEBAQEBAQEBAQEAAAABAQAAAAABAQEB" +
            "AQEAAAAAAQEBAQEBAQAAAAEAAAEBAQAAAAEBAQAAAAEBAQABAQE=");
    }
}
