using System.Collections.Generic;
using System.IO;
using Sdo.Osu;
using UnityEngine;

namespace Sdo.Game
{
    /// <summary>
    /// The dance of an external (user <c>Songs/</c>) song. osu!/StepMania charts ship no choreography, so the dancer
    /// used to fall back to one looping clip; instead one is GENERATED ONCE, exactly like the CD disc:
    /// <see cref="RandomDps"/> plans it, the .dps is written into the song's own folder, and its name is recorded in
    /// that folder's <see cref="SongSidecar"/> (<c>sdoinfo.dat</c>) — the file the disc is already recorded in. Every
    /// later play reads the sidecar and loads the file; nothing is regenerated. (Delete the <c>#DPS</c> line to get a
    /// fresh one.)
    ///
    /// The dance is DETERMINISTIC: the RNG seed is the song's identity (its folder + which song in it), so the same
    /// song always dances the same way — even if the sidecar is deleted, or the song is played on another machine.
    ///
    /// It is also the SAME dance whichever difficulty is played: everything the plan depends on — the seed, the length
    /// and the beat grid — is per-SONG (see <see cref="DanceInputs"/>), never per-chart. The dance still starts on the
    /// played difficulty's own first note (ScreenGameplay._danceStartSec), so the dancer holds its standby idle through
    /// the intro and starts moving on the first note; only WHAT it dances is shared.
    /// </summary>
    public static class ExternalDps
    {
        /// <summary>Shortest span worth choreographing (s).</summary>
        private const double MinDanceSeconds = 4.0;

        /// <summary>
        /// Absolute path of the song's .dps — the recorded one, else one generated (and recorded) now, else "" (the
        /// caller then keeps the fallback dance clip).
        /// </summary>
        /// <param name="map">The loaded chart — only the FALLBACK source of length/tempo, for a song whose charts can't
        /// be measured or whose BPM is unknown (see <see cref="DanceInputs"/>); planning off it directly is what used
        /// to make the dance depend on the difficulty played first.</param>
        /// <param name="songBpm">The catalog's per-song BPM (&lt;= 0 = unknown → the chart's own).</param>
        /// <param name="chartFormat">Sdo.Osu.SongFormat of this song's charts (1=osu, 2=sm, 3=.gn 包, 4=.mc).</param>
        /// <param name="chartSeed">.gn pack key, for a packed song's charts.</param>
        /// <param name="chartPaths">EVERY difficulty's chart file (empty slots may be "" / null) — their note windows,
        /// unioned, are the dance's length.</param>
        /// <param name="chartIndices">Per-slot .sm block / .gn difficulty index, parallel to <paramref name="chartPaths"/>.</param>
        public static string EnsureFor(string folderPath, string songKey, OsuBeatmap map, double songBpm,
                                       int chartFormat, long chartSeed,
                                       IReadOnlyList<string> chartPaths, IReadOnlyList<int> chartIndices)
        {
            if (string.IsNullOrEmpty(folderPath) || map == null || map.HitObjects.Count == 0) return "";
            songKey = songKey ?? "";

            string text = SongSidecar.ReadText(folderPath);   // current name, else the legacy sdo.header
            var recorded = SongSidecar.Find(SongSidecar.Parse(text), songKey);
            if (recorded != null && !string.IsNullOrEmpty(recorded.Dps) && recorded.DpsVersion >= SongSidecar.DpsGenerator)
            {
                string had = Path.Combine(folderPath, recorded.Dps);
                if (File.Exists(had)) return had;            // generated by an earlier run → reuse, never rebuild
            }
            // …but a dance an OLDER generator built is rebuilt once: a fix to the choreography has to reach the songs
            // the player has already danced (the seed is unchanged, so the new dance is still this song's own).

            // Length and tempo come from the SONG, not from the chart in hand — otherwise the same song choreographs
            // differently depending on which difficulty reached this first (see DanceInputs). Every difficulty is
            // re-read here, as written: this runs once per song, and gameplay's copy of the chart has already been
            // through lead-in/collapse by now.
            var windows = ExternalChartIO.Windows(chartFormat, chartPaths, chartIndices, chartSeed);
            var inputs = DanceInputs.For(DanceInputs.UnionSeconds(windows), songBpm,
                                         (map.LastNoteMs - map.FirstNoteMs) / 1000.0, map.Bpm);
            if (inputs.Seconds < MinDanceSeconds) return "";
            if (DpsMotionLibrary.Pool.Count == 0) return "";  // no motions in the data tree → nothing to plan with

            var req = new RandomDpsRequest
            {
                Bpm = inputs.Bpm,
                DanceSeconds = inputs.Seconds,
                Pool = DpsMotionLibrary.Pool,
                Intros = DpsMotionLibrary.Intros,
                Groups = DpsMotionLibrary.Groups,
                FrameCount = DpsMotionLibrary.Frames,
                Seed = SeedFor(folderPath, songKey),
                ChartName = "ext_" + RandomDps.Fnv(IdentityOf(folderPath, songKey)).ToString("x8") + ".gn",
            };

            byte[] dps = RandomDps.Build(req);
            if (dps.Length == 0) { SdoLog.Note("dps", "nothing planned for " + folderPath); return ""; }

            string file = SongSidecar.DpsFileName(songKey);
            string path = Path.Combine(folderPath, file);
            try
            {
                File.WriteAllBytes(path, dps);
                SongSidecar.WriteText(folderPath, SongSidecar.SetDps(text, songKey, file));
            }
            catch (System.Exception ex)
            {
                SdoLog.Note("dps", "could not write " + path + ": " + ex.Message);
                return "";                                   // read-only folder → dancer keeps the fallback clip
            }
            Debug.Log($"[dps] generated {file} for {Path.GetFileName(folderPath)}: {inputs.Seconds:F1}s @ {req.Bpm:F1} bpm, " +
                      $"seed {req.Seed:x8}, {windows.Count} difficult(y/ies) measured" +
                      $"{(inputs.PerSong ? "" : " — FELL BACK to this chart's own span/bpm")}");
            return path;
        }

        // Seed = the song's identity, NOT its path on this disk: the folder's NAME (a moved library keeps its dances)
        // plus which song in it. Same song ⇒ same seed ⇒ same dance, on any machine, forever.
        private static uint SeedFor(string folderPath, string songKey) => RandomDps.Fnv(IdentityOf(folderPath, songKey));

        private static string IdentityOf(string folderPath, string songKey)
        {
            string leaf = "";
            try { leaf = Path.GetFileName(folderPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)); }
            catch { leaf = folderPath ?? ""; }
            return (leaf ?? "").ToLowerInvariant() + "|" + (songKey ?? "").ToLowerInvariant();
        }
    }
}
