using System.IO;
using Sdo.Osu;
using UnityEngine;

namespace Sdo.Game
{
    /// <summary>
    /// The dance of an external (user <c>Songs/</c>) song. osu!/StepMania charts ship no choreography, so the dancer
    /// used to fall back to one looping clip; instead one is GENERATED ONCE, exactly like the CD disc:
    /// <see cref="RandomDps"/> plans it, the .dps is written into the song's own folder, and its name is recorded in
    /// that folder's <see cref="SongSidecar"/> (<c>sdo.header</c>) — the file the disc is already recorded in. Every
    /// later play reads the sidecar and loads the file; nothing is regenerated. (Delete the <c>#DPS</c> line to get a
    /// fresh one.)
    ///
    /// The dance is DETERMINISTIC: the RNG seed is the song's identity (its folder + which song in it), so the same
    /// song always dances the same way — even if the sidecar is deleted, or the song is played on another machine.
    ///
    /// It spans first note → last note, which is exactly the window the engine's dance clock covers
    /// (ScreenGameplay._danceStartSec = the first note), so the dancer holds its standby idle through the intro and
    /// starts moving on the first note.
    /// </summary>
    public static class ExternalDps
    {
        /// <summary>Shortest span worth choreographing (s).</summary>
        private const double MinDanceSeconds = 4.0;

        /// <summary>
        /// Absolute path of the song's .dps — the recorded one, else one generated (and recorded) now, else "" (the
        /// caller then keeps the fallback dance clip). <paramref name="map"/> is the loaded chart: its first/last note
        /// set the span, its BPM the beat grid.
        /// </summary>
        public static string EnsureFor(string folderPath, string songKey, OsuBeatmap map)
        {
            if (string.IsNullOrEmpty(folderPath) || map == null || map.HitObjects.Count == 0) return "";
            songKey = songKey ?? "";

            string sidecar = Path.Combine(folderPath, SongSidecar.FileName);
            string text = ReadText(sidecar);
            var recorded = SongSidecar.Find(SongSidecar.Parse(text), songKey);
            if (recorded != null && !string.IsNullOrEmpty(recorded.Dps) && recorded.DpsVersion >= SongSidecar.DpsGenerator)
            {
                string had = Path.Combine(folderPath, recorded.Dps);
                if (File.Exists(had)) return had;            // generated by an earlier run → reuse, never rebuild
            }
            // …but a dance an OLDER generator built is rebuilt once: a fix to the choreography has to reach the songs
            // the player has already danced (the seed is unchanged, so the new dance is still this song's own).

            double span = (map.LastNoteMs - map.FirstNoteMs) / 1000.0;
            if (span < MinDanceSeconds) return "";
            if (DpsMotionLibrary.Pool.Count == 0) return "";  // no motions in the data tree → nothing to plan with

            var req = new RandomDpsRequest
            {
                Bpm = map.Bpm > 0 ? map.Bpm : 120.0,
                DanceSeconds = span,
                Pool = DpsMotionLibrary.Pool,
                Intros = DpsMotionLibrary.Intros,
                FrameCount = DpsMotionLibrary.Frames,
                Seed = SeedFor(folderPath, songKey),
                ChartName = "ext_" + RandomDps.Fnv(IdentityOf(folderPath, songKey)).ToString("x8") + ".gn",
            };

            byte[] dps = RandomDps.Build(req);
            if (dps.Length == 0) { SdoLog.Note("dps", "nothing planned for " + folderPath); return ""; }

            string file = SongSidecar.DpsFileName(songKey);
            string path = Path.Combine(folderPath, file);
            try
            {
                File.WriteAllBytes(path, dps);
                File.WriteAllText(sidecar, SongSidecar.SetDps(text, songKey, file));
            }
            catch (System.Exception ex)
            {
                SdoLog.Note("dps", "could not write " + path + ": " + ex.Message);
                return "";                                   // read-only folder → dancer keeps the fallback clip
            }
            Debug.Log($"[dps] generated {file} for {Path.GetFileName(folderPath)}: {span:F1}s @ {req.Bpm:F1} bpm, seed {req.Seed:x8}");
            return path;
        }

        // Seed = the song's identity, NOT its path on this disk: the folder's NAME (a moved library keeps its dances)
        // plus which song in it. Same song ⇒ same seed ⇒ same dance, on any machine, forever.
        private static uint SeedFor(string folderPath, string songKey) => RandomDps.Fnv(IdentityOf(folderPath, songKey));

        private static string IdentityOf(string folderPath, string songKey)
        {
            string leaf = "";
            try { leaf = Path.GetFileName(folderPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)); }
            catch { leaf = folderPath ?? ""; }
            return (leaf ?? "").ToLowerInvariant() + "|" + (songKey ?? "").ToLowerInvariant();
        }

        private static string ReadText(string path)
        {
            try { return File.Exists(path) ? File.ReadAllText(path) : ""; }
            catch { return ""; }
        }
    }
}
