// <auto-generated>
//   Generated by tools/build_scene_mapobj_catalog.py from
//   docs/reverse-engineering/SDO_SCENE_MAPOBJ_TABLE.json, resolved against the
//   extracted SCENE/MAPOBJ tree on disk. DO NOT EDIT BY HAND.
// </auto-generated>
using System.Collections.Generic;

namespace Sdo.Game
{
    /// <summary>One placed instance of a mapobj (native SDO world coords, uniform scale).</summary>
    public struct MapobjPlacement
    {
        public readonly float X, Y, Z, Scale;
        public MapobjPlacement(float x, float y, float z, float scale) { X = x; Y = y; Z = z; Scale = scale; }
    }

    /// <summary>A mapobj prop group: one mesh/skeleton/motion loaded once, placed at N transforms.</summary>
    public sealed class MapobjGroup
    {
        public readonly string Folder;            // SCENE/MAPOBJ sub-folder of the .MSH (may be nested, e.g. "14_HAIDI/GUANG")
        public readonly string Msh, Hrc, Mot;     // file names within Folder (with extension); Mot may be null
        public readonly MapobjPlacement[] Instances;
        public MapobjGroup(string folder, string msh, string hrc, string mot, MapobjPlacement[] instances)
        { Folder = folder; Msh = msh; Hrc = hrc; Mot = mot; Instances = instances; }
    }

    /// <summary>
    /// Per-scene 3D stage props, generated from the decompiled Scene_LoadBackground table and resolved
    /// against the real extracted file tree. Keyed by the scene FOLDER name (last segment of
    /// ScreenGameplay.scenePath, e.g. "SCN0009"). Scenes with no mapobj — or unknown folders — return an empty
    /// list. 2D billboards / lights / particle effects are not included.
    /// </summary>
    public static class SceneMapobjCatalog
    {
        private static readonly IReadOnlyList<MapobjGroup> Empty = new MapobjGroup[0];
        private static readonly Dictionary<string, MapobjGroup[]> ByFolder = Build();

        /// <summary>Mapobjs for a scene folder (e.g. "SCN0009"); empty list if none / unknown.</summary>
        public static IReadOnlyList<MapobjGroup> ForFolder(string folder)
        {
            if (string.IsNullOrEmpty(folder)) return Empty;
            return ByFolder.TryGetValue(folder.ToUpperInvariant(), out var g) ? g : Empty;
        }

        private static Dictionary<string, MapobjGroup[]> Build()
        {
            return new Dictionary<string, MapobjGroup[]>
            {
                ["SCN0000"] = new[]
                {
                    new MapobjGroup("HUISHOU", "HUISHOU.MSH", "HUISHOU.HRC", "HUISHOU.MOT", new[]
                    {
                        new MapobjPlacement(-56.555f, 101.897f, 275.672f, 1f),
                    }),
                    new MapobjGroup("ZHAOPAI", "ZHAOPAI.MSH", "ZHAOPAI.HRC", "ZHAOPAI.MOT", new[]
                    {
                        new MapobjPlacement(-183.498f, 2.294f, 239.456f, 1f),
                    }),
                },
                ["SCN0003"] = new[]
                {
                    new MapobjGroup("BOX", "BOX.MSH", "BOX.HRC", null, new[]
                    {
                        new MapobjPlacement(-154.523f, 0f, 0f, 1f), new MapobjPlacement(-144.222f, 0f, 10.301f, 1f), new MapobjPlacement(-133.921f, 0f, 20.602f, 1f),
                        new MapobjPlacement(-123.62f, 0f, 30.903f, 1f), new MapobjPlacement(-113.318f, 0f, 41.205f, 1f), new MapobjPlacement(-103.017f, 0f, 51.506f, 1f),
                        new MapobjPlacement(-92.716f, 0f, 61.807f, 1f), new MapobjPlacement(-82.415f, 0f, 72.108f, 1f), new MapobjPlacement(-72.114f, 0f, 82.409f, 1f),
                        new MapobjPlacement(-61.813f, 0f, 92.71f, 1f), new MapobjPlacement(-51.512f, 0f, 103.011f, 1f), new MapobjPlacement(-41.211f, 0f, 113.312f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 123.614f, 1f), new MapobjPlacement(-20.608f, 0f, 133.915f, 1f), new MapobjPlacement(-10.307f, 0f, 144.216f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 154.517f, 1f), new MapobjPlacement(-144.222f, 0f, -10.301f, 1f), new MapobjPlacement(-133.921f, 0f, 0f, 1f),
                        new MapobjPlacement(-123.62f, 0f, 10.301f, 1f), new MapobjPlacement(-113.318f, 0f, 20.602f, 1f), new MapobjPlacement(-103.017f, 0f, 30.903f, 1f),
                        new MapobjPlacement(-92.716f, 0f, 41.205f, 1f), new MapobjPlacement(-82.415f, 0f, 51.506f, 1f), new MapobjPlacement(-72.114f, 0f, 61.807f, 1f),
                        new MapobjPlacement(-61.813f, 0f, 72.108f, 1f), new MapobjPlacement(-51.512f, 0f, 82.409f, 1f), new MapobjPlacement(-41.211f, 0f, 92.71f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 103.011f, 1f), new MapobjPlacement(-20.608f, 0f, 113.312f, 1f), new MapobjPlacement(-10.307f, 0f, 123.614f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 133.915f, 1f), new MapobjPlacement(10.295f, 0f, 144.216f, 1f), new MapobjPlacement(-133.921f, 0f, -20.602f, 1f),
                        new MapobjPlacement(-123.62f, 0f, -10.301f, 1f), new MapobjPlacement(-113.318f, 0f, 0f, 1f), new MapobjPlacement(-103.017f, 0f, 10.301f, 1f),
                        new MapobjPlacement(-92.716f, 0f, 20.602f, 1f), new MapobjPlacement(-82.415f, 0f, 30.903f, 1f), new MapobjPlacement(-72.114f, 0f, 41.205f, 1f),
                        new MapobjPlacement(-61.813f, 0f, 51.506f, 1f), new MapobjPlacement(-51.512f, 0f, 61.807f, 1f), new MapobjPlacement(-41.211f, 0f, 72.108f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 82.409f, 1f), new MapobjPlacement(-20.608f, 0f, 92.71f, 1f), new MapobjPlacement(-10.307f, 0f, 103.011f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 113.312f, 1f), new MapobjPlacement(10.295f, 0f, 123.614f, 1f), new MapobjPlacement(20.596f, 0f, 133.915f, 1f),
                        new MapobjPlacement(-123.62f, 0f, -30.903f, 1f), new MapobjPlacement(-113.318f, 0f, -20.602f, 1f), new MapobjPlacement(-103.017f, 0f, -10.301f, 1f),
                        new MapobjPlacement(-92.716f, 0f, 0f, 1f), new MapobjPlacement(-82.415f, 0f, 10.301f, 1f), new MapobjPlacement(-72.114f, 0f, 20.602f, 1f),
                        new MapobjPlacement(-61.813f, 0f, 30.903f, 1f), new MapobjPlacement(-51.512f, 0f, 41.205f, 1f), new MapobjPlacement(-41.211f, 0f, 51.506f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 61.807f, 1f), new MapobjPlacement(-20.608f, 0f, 72.108f, 1f), new MapobjPlacement(-10.307f, 0f, 82.409f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 92.71f, 1f), new MapobjPlacement(10.295f, 0f, 103.011f, 1f), new MapobjPlacement(20.596f, 0f, 113.312f, 1f),
                        new MapobjPlacement(30.897f, 0f, 123.614f, 1f), new MapobjPlacement(-113.318f, 0f, -41.205f, 1f), new MapobjPlacement(-103.017f, 0f, -30.903f, 1f),
                        new MapobjPlacement(-92.716f, 0f, -20.602f, 1f), new MapobjPlacement(-82.415f, 0f, -10.301f, 1f), new MapobjPlacement(-72.114f, 0f, 0f, 1f),
                        new MapobjPlacement(-61.813f, 0f, 10.301f, 1f), new MapobjPlacement(-51.512f, 0f, 20.602f, 1f), new MapobjPlacement(-41.211f, 0f, 30.903f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 41.205f, 1f), new MapobjPlacement(-20.608f, 0f, 51.506f, 1f), new MapobjPlacement(-10.307f, 0f, 61.807f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 72.108f, 1f), new MapobjPlacement(10.295f, 0f, 82.409f, 1f), new MapobjPlacement(20.596f, 0f, 92.71f, 1f),
                        new MapobjPlacement(30.897f, 0f, 103.011f, 1f), new MapobjPlacement(41.198f, 0f, 113.312f, 1f), new MapobjPlacement(-103.017f, 0f, -51.506f, 1f),
                        new MapobjPlacement(-92.716f, 0f, -41.205f, 1f), new MapobjPlacement(-82.415f, 0f, -30.903f, 1f), new MapobjPlacement(-72.114f, 0f, -20.602f, 1f),
                        new MapobjPlacement(-61.813f, 0f, -10.301f, 1f), new MapobjPlacement(-51.512f, 0f, 0f, 1f), new MapobjPlacement(-41.211f, 0f, 10.301f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 20.602f, 1f), new MapobjPlacement(-20.608f, 0f, 30.903f, 1f), new MapobjPlacement(-10.307f, 0f, 41.205f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 51.506f, 1f), new MapobjPlacement(10.295f, 0f, 61.807f, 1f), new MapobjPlacement(20.596f, 0f, 72.108f, 1f),
                        new MapobjPlacement(30.897f, 0f, 82.409f, 1f), new MapobjPlacement(41.198f, 0f, 92.71f, 1f), new MapobjPlacement(51.5f, 0f, 103.011f, 1f),
                        new MapobjPlacement(-92.716f, 0f, -61.807f, 1f), new MapobjPlacement(-82.415f, 0f, -51.506f, 1f), new MapobjPlacement(-72.114f, 0f, -41.205f, 1f),
                        new MapobjPlacement(-61.813f, 0f, -30.903f, 1f), new MapobjPlacement(-51.512f, 0f, -20.602f, 1f), new MapobjPlacement(-41.211f, 0f, -10.301f, 1f),
                        new MapobjPlacement(-30.909f, 0f, 0f, 1f), new MapobjPlacement(-20.608f, 0f, 10.301f, 1f), new MapobjPlacement(-10.307f, 0f, 20.602f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 30.903f, 1f), new MapobjPlacement(10.295f, 0f, 41.205f, 1f), new MapobjPlacement(20.596f, 0f, 51.506f, 1f),
                        new MapobjPlacement(30.897f, 0f, 61.807f, 1f), new MapobjPlacement(41.198f, 0f, 72.108f, 1f), new MapobjPlacement(51.5f, 0f, 82.409f, 1f),
                        new MapobjPlacement(61.801f, 0f, 92.71f, 1f), new MapobjPlacement(-82.415f, 0f, -72.108f, 1f), new MapobjPlacement(-72.114f, 0f, -61.807f, 1f),
                        new MapobjPlacement(-61.813f, 0f, -51.506f, 1f), new MapobjPlacement(-51.512f, 0f, -41.205f, 1f), new MapobjPlacement(-41.211f, 0f, -30.903f, 1f),
                        new MapobjPlacement(-30.909f, 0f, -20.602f, 1f), new MapobjPlacement(-20.608f, 0f, -10.301f, 1f), new MapobjPlacement(-10.307f, 0f, 0f, 1f),
                        new MapobjPlacement(-0.006f, 0f, 10.301f, 1f), new MapobjPlacement(10.295f, 0f, 20.602f, 1f), new MapobjPlacement(20.596f, 0f, 30.903f, 1f),
                        new MapobjPlacement(30.897f, 0f, 41.205f, 1f), new MapobjPlacement(41.198f, 0f, 51.506f, 1f), new MapobjPlacement(51.5f, 0f, 61.807f, 1f),
                        new MapobjPlacement(61.801f, 0f, 72.108f, 1f), new MapobjPlacement(72.102f, 0f, 82.409f, 1f), new MapobjPlacement(-72.114f, 0f, -82.409f, 1f),
                        new MapobjPlacement(-61.813f, 0f, -72.108f, 1f), new MapobjPlacement(-51.512f, 0f, -61.807f, 1f), new MapobjPlacement(-41.211f, 0f, -51.506f, 1f),
                        new MapobjPlacement(-30.909f, 0f, -41.205f, 1f), new MapobjPlacement(-20.608f, 0f, -30.903f, 1f), new MapobjPlacement(-10.307f, 0f, -20.602f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -10.301f, 1f), new MapobjPlacement(10.295f, 0f, 0f, 1f), new MapobjPlacement(20.596f, 0f, 10.301f, 1f),
                        new MapobjPlacement(30.897f, 0f, 20.602f, 1f), new MapobjPlacement(41.198f, 0f, 30.903f, 1f), new MapobjPlacement(51.5f, 0f, 41.205f, 1f),
                        new MapobjPlacement(61.801f, 0f, 51.506f, 1f), new MapobjPlacement(72.102f, 0f, 61.807f, 1f), new MapobjPlacement(82.403f, 0f, 72.108f, 1f),
                        new MapobjPlacement(-61.813f, 0f, -92.71f, 1f), new MapobjPlacement(-51.512f, 0f, -82.409f, 1f), new MapobjPlacement(-41.211f, 0f, -72.108f, 1f),
                        new MapobjPlacement(-30.909f, 0f, -61.807f, 1f), new MapobjPlacement(-20.608f, 0f, -51.506f, 1f), new MapobjPlacement(-10.307f, 0f, -41.205f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -30.903f, 1f), new MapobjPlacement(10.295f, 0f, -20.602f, 1f), new MapobjPlacement(20.596f, 0f, -10.301f, 1f),
                        new MapobjPlacement(30.897f, 0f, 0f, 1f), new MapobjPlacement(41.198f, 0f, 10.301f, 1f), new MapobjPlacement(51.5f, 0f, 20.602f, 1f),
                        new MapobjPlacement(61.801f, 0f, 30.903f, 1f), new MapobjPlacement(72.102f, 0f, 41.205f, 1f), new MapobjPlacement(82.403f, 0f, 51.506f, 1f),
                        new MapobjPlacement(92.704f, 0f, 61.807f, 1f), new MapobjPlacement(-51.512f, 0f, -103.011f, 1f), new MapobjPlacement(-41.211f, 0f, -92.71f, 1f),
                        new MapobjPlacement(-30.909f, 0f, -82.409f, 1f), new MapobjPlacement(-20.608f, 0f, -72.108f, 1f), new MapobjPlacement(-10.307f, 0f, -61.807f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -51.506f, 1f), new MapobjPlacement(10.295f, 0f, -41.205f, 1f), new MapobjPlacement(20.596f, 0f, -30.903f, 1f),
                        new MapobjPlacement(30.897f, 0f, -20.602f, 1f), new MapobjPlacement(41.198f, 0f, -10.301f, 1f), new MapobjPlacement(51.5f, 0f, 0f, 1f),
                        new MapobjPlacement(61.801f, 0f, 10.301f, 1f), new MapobjPlacement(72.102f, 0f, 20.602f, 1f), new MapobjPlacement(82.403f, 0f, 30.903f, 1f),
                        new MapobjPlacement(92.704f, 0f, 41.205f, 1f), new MapobjPlacement(103.005f, 0f, 51.506f, 1f), new MapobjPlacement(-41.211f, 0f, -113.312f, 1f),
                        new MapobjPlacement(-30.909f, 0f, -103.011f, 1f), new MapobjPlacement(-20.608f, 0f, -92.71f, 1f), new MapobjPlacement(-10.307f, 0f, -82.409f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -72.108f, 1f), new MapobjPlacement(10.295f, 0f, -61.807f, 1f), new MapobjPlacement(20.596f, 0f, -51.506f, 1f),
                        new MapobjPlacement(30.897f, 0f, -41.205f, 1f), new MapobjPlacement(41.198f, 0f, -30.903f, 1f), new MapobjPlacement(51.5f, 0f, -20.602f, 1f),
                        new MapobjPlacement(61.801f, 0f, -10.301f, 1f), new MapobjPlacement(72.102f, 0f, 0f, 1f), new MapobjPlacement(82.403f, 0f, 10.301f, 1f),
                        new MapobjPlacement(92.704f, 0f, 20.602f, 1f), new MapobjPlacement(103.005f, 0f, 30.903f, 1f), new MapobjPlacement(113.306f, 0f, 41.205f, 1f),
                        new MapobjPlacement(-30.909f, 0f, -123.614f, 1f), new MapobjPlacement(-20.608f, 0f, -113.312f, 1f), new MapobjPlacement(-10.307f, 0f, -103.011f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -92.71f, 1f), new MapobjPlacement(10.295f, 0f, -82.409f, 1f), new MapobjPlacement(20.596f, 0f, -72.108f, 1f),
                        new MapobjPlacement(30.897f, 0f, -61.807f, 1f), new MapobjPlacement(41.198f, 0f, -51.506f, 1f), new MapobjPlacement(51.5f, 0f, -41.205f, 1f),
                        new MapobjPlacement(61.801f, 0f, -30.903f, 1f), new MapobjPlacement(72.102f, 0f, -20.602f, 1f), new MapobjPlacement(82.403f, 0f, -10.301f, 1f),
                        new MapobjPlacement(92.704f, 0f, 0f, 1f), new MapobjPlacement(103.005f, 0f, 10.301f, 1f), new MapobjPlacement(113.306f, 0f, 20.602f, 1f),
                        new MapobjPlacement(123.608f, 0f, 30.903f, 1f), new MapobjPlacement(-20.608f, 0f, -133.915f, 1f), new MapobjPlacement(-10.307f, 0f, -123.614f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -113.312f, 1f), new MapobjPlacement(10.295f, 0f, -103.011f, 1f), new MapobjPlacement(20.596f, 0f, -92.71f, 1f),
                        new MapobjPlacement(30.897f, 0f, -82.409f, 1f), new MapobjPlacement(41.198f, 0f, -72.108f, 1f), new MapobjPlacement(51.5f, 0f, -61.807f, 1f),
                        new MapobjPlacement(61.801f, 0f, -51.506f, 1f), new MapobjPlacement(72.102f, 0f, -41.205f, 1f), new MapobjPlacement(82.403f, 0f, -30.903f, 1f),
                        new MapobjPlacement(92.704f, 0f, -20.602f, 1f), new MapobjPlacement(103.005f, 0f, -10.301f, 1f), new MapobjPlacement(113.306f, 0f, 0f, 1f),
                        new MapobjPlacement(123.608f, 0f, 10.301f, 1f), new MapobjPlacement(133.909f, 0f, 20.602f, 1f), new MapobjPlacement(-10.307f, 0f, -144.216f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -133.915f, 1f), new MapobjPlacement(10.295f, 0f, -123.614f, 1f), new MapobjPlacement(20.596f, 0f, -113.312f, 1f),
                        new MapobjPlacement(30.897f, 0f, -103.011f, 1f), new MapobjPlacement(41.198f, 0f, -92.71f, 1f), new MapobjPlacement(51.5f, 0f, -82.409f, 1f),
                        new MapobjPlacement(61.801f, 0f, -72.108f, 1f), new MapobjPlacement(72.102f, 0f, -61.807f, 1f), new MapobjPlacement(82.403f, 0f, -51.506f, 1f),
                        new MapobjPlacement(92.704f, 0f, -41.205f, 1f), new MapobjPlacement(103.005f, 0f, -30.903f, 1f), new MapobjPlacement(113.306f, 0f, -20.602f, 1f),
                        new MapobjPlacement(123.608f, 0f, -10.301f, 1f), new MapobjPlacement(133.909f, 0f, 0f, 1f), new MapobjPlacement(144.21f, 0f, 10.301f, 1f),
                        new MapobjPlacement(-0.006f, 0f, -154.517f, 1f), new MapobjPlacement(10.295f, 0f, -144.216f, 1f), new MapobjPlacement(20.596f, 0f, -133.915f, 1f),
                        new MapobjPlacement(30.897f, 0f, -123.614f, 1f), new MapobjPlacement(41.198f, 0f, -113.312f, 1f), new MapobjPlacement(51.5f, 0f, -103.011f, 1f),
                        new MapobjPlacement(61.801f, 0f, -92.71f, 1f), new MapobjPlacement(72.102f, 0f, -82.409f, 1f), new MapobjPlacement(82.403f, 0f, -72.108f, 1f),
                        new MapobjPlacement(92.704f, 0f, -61.807f, 1f), new MapobjPlacement(103.005f, 0f, -51.506f, 1f), new MapobjPlacement(113.306f, 0f, -41.205f, 1f),
                        new MapobjPlacement(123.608f, 0f, -30.903f, 1f), new MapobjPlacement(133.909f, 0f, -20.602f, 1f), new MapobjPlacement(144.21f, 0f, -10.301f, 1f),
                        new MapobjPlacement(154.511f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("BALL", "BALL.MSH", "BALL.HRC", "BALL.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0004"] = new[]
                {
                    new MapobjGroup("SEA_UP", "SEA_UP.MSH", "SEA_UP.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SEA_DOWN", "SEA_DOWN.MSH", "SEA_DOWN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CHUAN", "CHUAN.MSH", "CHUAN.HRC", "CHUAN.MOT", new[]
                    {
                        new MapobjPlacement(-125f, -33f, 519f, 1f),
                    }),
                    new MapobjGroup("BEACH", "LANG.MSH", "LANG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SEA", "SEA.MSH", "SEA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0005"] = new[]
                {
                    new MapobjGroup("CHRISTMAS", "CHRISTMAS.MSH", "CHRISTMAS.HRC", "CHRISTMAS.MOT", new[]
                    {
                        new MapobjPlacement(105f, -33f, 236f, 1f),
                    }),
                    new MapobjGroup("MERRYCHRISTMAS", "MERRYCHRISTMAS.MSH", "MERRYCHRISTMAS.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0006"] = new[]
                {
                    new MapobjGroup("DENG", "DENG.MSH", "DENG.HRC", null, new[]
                    {
                        new MapobjPlacement(-196.852f, 87.769f, 117.997f, 1f), new MapobjPlacement(-194.231f, 89.174f, 123.617f, 1f), new MapobjPlacement(-191.667f, 90.309f, 129.116f, 1f),
                        new MapobjPlacement(-189.012f, 91.657f, 134.809f, 1f), new MapobjPlacement(-186.277f, 93.129f, 140.673f, 1f), new MapobjPlacement(-183.742f, 94.399f, 146.111f, 1f),
                        new MapobjPlacement(-180.59f, 95.628f, 152.869f, 1f), new MapobjPlacement(-177.688f, 96.972f, 159.093f, 1f), new MapobjPlacement(-174.95f, 98.261f, 164.966f, 1f),
                        new MapobjPlacement(-172.185f, 99.413f, 170.894f, 1f), new MapobjPlacement(-169.367f, 100.564f, 176.938f, 1f), new MapobjPlacement(-165.841f, 101.915f, 184.499f, 1f),
                        new MapobjPlacement(-162.716f, 102.861f, 191.2f, 1f), new MapobjPlacement(-159.897f, 103.409f, 197.247f, 1f), new MapobjPlacement(-156.994f, 104.091f, 203.472f, 1f),
                        new MapobjPlacement(-154.094f, 104.436f, 209.69f, 1f), new MapobjPlacement(-151.339f, 105.049f, 215.598f, 1f), new MapobjPlacement(-148.491f, 105.465f, 221.706f, 1f),
                        new MapobjPlacement(-144.765f, 105.745f, 229.697f, 1f), new MapobjPlacement(-141.98f, 105.824f, 235.669f, 1f), new MapobjPlacement(-139.112f, 105.902f, 241.819f, 1f),
                        new MapobjPlacement(-136.247f, 106.115f, 247.963f, 1f), new MapobjPlacement(-133.317f, 105.99f, 254.248f, 1f), new MapobjPlacement(-130.446f, 105.73f, 260.404f, 1f),
                        new MapobjPlacement(-130.446f, 99.542f, 260.404f, 1f), new MapobjPlacement(-130.446f, 93.354f, 260.404f, 1f), new MapobjPlacement(-130.446f, 87.166f, 260.404f, 1f),
                        new MapobjPlacement(-130.446f, 80.978f, 260.404f, 1f), new MapobjPlacement(-132.979f, 79.85f, 254.971f, 1f), new MapobjPlacement(-135.879f, 79.799f, 248.752f, 1f),
                        new MapobjPlacement(-138.891f, 79.747f, 242.295f, 1f), new MapobjPlacement(-141.707f, 79.759f, 236.254f, 1f), new MapobjPlacement(-144.578f, 79.77f, 230.097f, 1f),
                        new MapobjPlacement(-147.418f, 79.726f, 224.007f, 1f), new MapobjPlacement(-150.255f, 79.401f, 217.923f, 1f), new MapobjPlacement(-152.986f, 78.868f, 212.067f, 1f),
                        new MapobjPlacement(-155.884f, 78.2f, 205.851f, 1f), new MapobjPlacement(-158.752f, 77.601f, 199.702f, 1f), new MapobjPlacement(-161.588f, 77.07f, 193.62f, 1f),
                        new MapobjPlacement(-164.535f, 76.338f, 187.3f, 1f), new MapobjPlacement(-167.212f, 75.333f, 181.56f, 1f), new MapobjPlacement(-169.971f, 74.195f, 175.642f, 1f),
                        new MapobjPlacement(-172.671f, 72.992f, 169.852f, 1f), new MapobjPlacement(-175.596f, 71.723f, 163.58f, 1f), new MapobjPlacement(-178.404f, 70.589f, 157.557f, 1f),
                        new MapobjPlacement(-181.874f, 69.116f, 150.117f, 1f), new MapobjPlacement(-184.715f, 67.578f, 144.025f, 1f), new MapobjPlacement(-187.61f, 66.176f, 137.816f, 1f),
                        new MapobjPlacement(-190.596f, 64.771f, 131.412f, 1f), new MapobjPlacement(-193.551f, 63.167f, 125.075f, 1f), new MapobjPlacement(-196.389f, 61.833f, 118.988f, 1f),
                        new MapobjPlacement(-199.282f, 60.434f, 112.785f, 1f), new MapobjPlacement(-199.282f, 66.912f, 112.785f, 1f), new MapobjPlacement(-199.282f, 73.358f, 112.785f, 1f),
                        new MapobjPlacement(-199.282f, 79.676f, 112.785f, 1f), new MapobjPlacement(-199.313f, 86.233f, 112.718f, 1f), new MapobjPlacement(-182.939f, 121.997f, 167.559f, 1f),
                        new MapobjPlacement(-180.763f, 126.866f, 172.226f, 1f), new MapobjPlacement(-178.366f, 130.307f, 177.365f, 1f), new MapobjPlacement(-175.896f, 132.143f, 182.663f, 1f),
                        new MapobjPlacement(-173.278f, 132.733f, 188.278f, 1f), new MapobjPlacement(-170.662f, 131.508f, 193.887f, 1f), new MapobjPlacement(-168.162f, 128.672f, 199.248f, 1f),
                        new MapobjPlacement(-166.83f, 122.881f, 202.106f, 1f), new MapobjPlacement(-167.401f, 116.426f, 200.88f, 1f), new MapobjPlacement(-169.336f, 110.986f, 196.73f, 1f),
                        new MapobjPlacement(-171.752f, 108.041f, 191.55f, 1f), new MapobjPlacement(-174.279f, 106.51f, 186.13f, 1f), new MapobjPlacement(-177.094f, 106.182f, 180.095f, 1f),
                        new MapobjPlacement(-179.678f, 107.131f, 174.553f, 1f), new MapobjPlacement(-182.065f, 110.299f, 169.433f, 1f), new MapobjPlacement(-183.456f, 115.815f, 166.451f, 1f),
                    }),
                    new MapobjGroup("ZHUANPAN", "ZHUANPAN.MSH", "ZHUANPAN.HRC", "ZHUANPAN.MOT", new[]
                    {
                        new MapobjPlacement(114.56f, 0f, 329.529f, 1f),
                    }),
                },
                ["SCN0007"] = new[]
                {
                    new MapobjGroup("SKY", "SKY.MSH", "SKY.HRC", "SKY.MOT", new[]
                    {
                        new MapobjPlacement(7.935f, 0f, 38.449f, 1f),
                    }),
                },
                ["SCN0008"] = new[]
                {
                    new MapobjGroup("JINZITA", "JINZITA.MSH", "JINZITA.HRC", "JINZITA.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ZIMU", "ZIMU.MSH", "ZIMU.HRC", "ZIMU.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0009"] = new[]
                {
                    new MapobjGroup("GUATAN", "GUATAN.MSH", "GUATAN.HRC", "GUATAN.MOT", new[]
                    {
                        new MapobjPlacement(-45.79f, 0f, 0f, 1f), new MapobjPlacement(129.21f, 0f, -83f, 1f), new MapobjPlacement(-95.79f, 0f, 50f, 0.65f),
                        new MapobjPlacement(179.21f, 0f, -83f, 0.65f),
                    }),
                },
                ["SCN0010"] = new[]
                {
                    new MapobjGroup("HOUSE", "HOUSE.MSH", "HOUSE.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f), new MapobjPlacement(2168f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("MAO", "MAO.MSH", "MAO.HRC", "MAO.MOT", new[]
                    {
                        new MapobjPlacement(-140.636f, 69.757f, 170.121f, 1f),
                    }),
                    new MapobjGroup("QIQIU", "QIQIU.MSH", "QIQIU.HRC", "QIQIU.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("MAO1", "MAO1.MSH", "MAO1.HRC", "MAO1.MOT", new[]
                    {
                        new MapobjPlacement(140.636f, 69.754f, 170.121f, 1f),
                    }),
                },
                ["SCN0011"] = new[]
                {
                    new MapobjGroup("SCREEN", "SCREEN.MSH", "SCREEN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CAIDAI", "CAIDAI.MSH", "CAIDAI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("DENGGUANG", "DENGGUANG.MSH", "DENGGUANG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("DIDENG", "DIDENG.MSH", "DIDENG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("DINGDENG", "DINGDENG.MSH", "DINGDENG.HRC", "DINGDENG.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("DING", "DING.MSH", "DING.HRC", "DING.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIGUANG", "JIGUANG.MSH", "JIGUANG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LABA", "LABA.MSH", "LABA.HRC", "LABA.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0012"] = new[]
                {
                    new MapobjGroup("FIFA_GUANGGAO", "FIFA_GUANGGAO.MSH", "FIFA_GUANGGAO.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FIFA_RENQUN", "FIFA_RENQUN.MSH", "FIFA_RENQUN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FIFA_SHANGUANG", "FIFA_SHANGUANG.MSH", "FIFA_SHANGUANG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FIFA_QIUBEI", "FIFA_QIUBEI.MSH", "FIFA_QIUBEI.HRC", "FIFA_QIUBEI.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0013"] = new[]
                {
                    new MapobjGroup("FIFANIGHT_GUANGGAO", "FIFA_GUANGGAO.MSH", "FIFA_GUANGGAO.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FIFANIGHT_RENQUN", "FIFA_RENQUN.MSH", "FIFA_RENQUN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FIFANIGHT_SHANGUANG", "FIFA_SHANGUANG.MSH", "FIFA_SHANGUANG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FIFA_QIUBEI", "FIFA_QIUBEI.MSH", "FIFA_QIUBEI.HRC", "FIFA_QIUBEI.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0014"] = new[]
                {
                    new MapobjGroup("14_HAIDI/GUANG", "GUANG.MSH", "GUANG.HRC", "GUANG.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SHANHU-BAI", "SHANHU-BAI.MSH", "SHANHU-BAI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SHANHU-HONG", "SHANHU-HONG.MSH", "SHANHU-HONG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SHANHU-LV", "SHANHU-LV.MSH", "SHANHU-LV.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SHANHUZHI-BAI", "SHANHUZHI-BAI.MSH", "SHANHUZHI-BAI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SHANHUZHI-HONG", "SHANHUZHI-HONG.MSH", "SHANHUZHI-HONG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SHANHUZHI-LV", "SHANHUZHI-LV.MSH", "SHANHUZHI-LV.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/SEA_SCREEN", "SEA_SCREEN.MSH", "SEA_SCREEN.HRC", "SEA_SCREEN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("14_HAIDI/TV", "TV.MSH", "TV.HRC", "TV.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0015"] = new[]
                {
                    new MapobjGroup("15_DONGHUA/UV", "15_UV.MSH", "15_UV.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("15_DONGHUA/HUA", "15_HUA.MSH", "15_HUA.HRC", "15_HUA.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("15_DONGHUA/SHU1", "15_SHU1.MSH", "15_SHU1.HRC", "15_SHU1.MOT", new[]
                    {
                        new MapobjPlacement(-145.149f, 38.736f, 419.705f, 1f),
                    }),
                    new MapobjGroup("15_DONGHUA/SHU2", "15_SHU2.MSH", "15_SHU2.HRC", "15_SHU2.MOT", new[]
                    {
                        new MapobjPlacement(-79.26f, 40.744f, 433.129f, 1f),
                    }),
                    new MapobjGroup("15_DONGHUA/SHU3", "15_SHU3.MSH", "15_SHU3.HRC", "15_SHU3.MOT", new[]
                    {
                        new MapobjPlacement(-18.138f, 40.17f, 435.768f, 1f),
                    }),
                    new MapobjGroup("15_DONGHUA/SHU4", "15_SHU4.MSH", "15_SHU4.HRC", "15_SHU4.MOT", new[]
                    {
                        new MapobjPlacement(133.498f, 38.343f, 415.02f, 1f),
                    }),
                },
                ["SCN0016"] = new[]
                {
                    new MapobjGroup("16/DI/1", "DI1.MSH", "DI1.HRC", "DI1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/2", "DI2.MSH", "DI2.HRC", "DI2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/3", "DI3.MSH", "DI3.HRC", "DI3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/4", "DI4.MSH", "DI4.HRC", "DI4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/5", "DI5.MSH", "DI5.HRC", "DI5.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/6", "DI6.MSH", "DI6.HRC", "DI6.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/7", "DI7.MSH", "DI7.HRC", "DI7.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/8", "DI8.MSH", "DI8.HRC", "DI8.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/9", "DI9.MSH", "DI9.HRC", "DI9.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/10", "DI10.MSH", "DI10.HRC", "DI10.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/11", "DI11.MSH", "DI11.HRC", "DI11.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/12", "DI12.MSH", "DI12.HRC", "DI12.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/13", "DI13.MSH", "DI13.HRC", "DI13.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/14", "DI14.MSH", "DI14.HRC", "DI14.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/15", "DI15.MSH", "DI15.HRC", "DI15.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/16", "DI16.MSH", "DI16.HRC", "DI16.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/17", "DI17.MSH", "DI17.HRC", "DI17.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/18", "DI18.MSH", "DI18.HRC", "DI18.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/19", "DI19.MSH", "DI19.HRC", "DI19.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/20", "DI20.MSH", "DI20.HRC", "DI20.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/DI/21", "DI21.MSH", "DI21.HRC", "DI21.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/1", "FANGZI1.MSH", "FANGZI1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/2", "FANGZI2.MSH", "FANGZI2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/3", "FANGZI3.MSH", "FANGZI3.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/4", "FANGZI4.MSH", "FANGZI4.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/5", "FANGZI5.MSH", "FANGZI5.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/7", "FANGZI7.MSH", "FANGZI7.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/8", "FANGZI8.MSH", "FANGZI8.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/9", "FANGZI9.MSH", "FANGZI9.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/10", "FANGZI10.MSH", "FANGZI10.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/CHENGSHI", "CHENGSHI.MSH", "CHENGSHI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/_DENG1", "DENG1.MSH", "DENG1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/DENG2", "DENG2.MSH", "DENG2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/PAIZI", "PAIZI.MSH", "PAIZI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/FANGZI/XINTIANDI", "XINTIANDI.MSH", "XINTIANDI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/SKY", "SKY.MSH", "SKY.HRC", "SKY.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/JIGUANG1", "JIGUANG1.MSH", "JIGUANG1.HRC", "JIGUANG1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/JIGUANG2", "JIGUANG2.MSH", "JIGUANG2.HRC", "JIGUANG2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("16/JIGUANG3", "JIGUANG3.MSH", "JIGUANG3.HRC", "JIGUANG3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0017"] = new[]
                {
                    new MapobjGroup("17_DITIE/DIANSHI", "DIANSHI.MSH", "DIANSHI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/DIE1", "DIE1.MSH", "DIE1.HRC", "DIE1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/DIE2", "DIE2.MSH", "DIE2.HRC", "DIE2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/DIGUANG", "DIGUANG.MSH", "DIGUANG.HRC", "DIGUANG.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/FUSHOU1", "FUSHOU1.MSH", "FUSHOU1.HRC", "FUSHOU1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/FUSHOU2", "FUSHOU2.MSH", "FUSHOU2.HRC", "FUSHOU2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/GUANGQUAN", "GUANGQUAN.MSH", "GUANGQUAN.HRC", "GUANGQUAN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/LABA1", "LABA1.MSH", "LABA1.HRC", "LABA1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/LABA2", "LABA2.MSH", "LABA2.HRC", "LABA2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/SKY", "SKY.MSH", "SKY.HRC", "SKY.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/ZHAN", "ZHAN.MSH", "ZHAN.HRC", "ZHAN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("17_DITIE/ZHUZI", "ZHUZI.MSH", "ZHUZI.HRC", "ZHUZI.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0018"] = new[]
                {
                    new MapobjGroup("18_BOAT/BEIJING", "BEIJING.MSH", "BEIJING.HRC", "BEIJING.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/GUAJIAN1", "GUAJIAN1.MSH", "GUAJIAN1.HRC", "GUAJIAN1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/GUAJIAN2", "GUAJIAN2.MSH", "GUAJIAN2.HRC", "GUAJIAN2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/NIHONG", "NIHONG.MSH", "NIHONG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/QIAO", "QIAO.MSH", "QIAO.HRC", "QIAO.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/BOAT_SCREEN", "BOAT_SCREEN.MSH", "BOAT_SCREEN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/SHUIMO", "SHUIMO.MSH", "SHUIMO.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/WATER", "WATER.MSH", "WATER.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("18_BOAT/ZHUANDENG", "ZHUANDENG.MSH", "ZHUANDENG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0019"] = new[]
                {
                    new MapobjGroup("PK/GUANG1", "GUANG1.MSH", "GUANG1.HRC", "GUANG1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/GUANG2", "GUANG2.MSH", "GUANG2.HRC", "GUANG2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/GUANG3", "GUANG3.MSH", "GUANG3.HRC", "GUANG3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/GUANG4", "GUANG4.MSH", "GUANG4.HRC", "GUANG4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA1", "LABA1.MSH", "LABA1.HRC", "LABA1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA2", "LABA2.MSH", "LABA2.HRC", "LABA2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA3", "LABA3.MSH", "LABA3.HRC", "LABA3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA4", "LABA4.MSH", "LABA4.HRC", "LABA4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA5", "LABA5.MSH", "LABA5.HRC", "LABA5.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA6", "LABA6.MSH", "LABA6.HRC", "LABA6.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA7", "LABA7.MSH", "LABA7.HRC", "LABA7.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA8", "LABA8.MSH", "LABA8.HRC", "LABA8.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA9", "LABA9.MSH", "LABA9.HRC", "LABA9.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA10", "LABA10.MSH", "LABA10.HRC", "LABA10.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/LABA11", "LABA11.MSH", "LABA11.HRC", "LABA11.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/SHAN", "SHAN.MSH", "SHAN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("PK/ZHUAN", "ZHUAN.MSH", "ZHUAN.HRC", "ZHUAN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0020"] = new[]
                {
                    new MapobjGroup("19_SUBWAY/VT1", "TV1.MSH", "TV1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("19_SUBWAY/VT6", "TV6.MSH", "TV6.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("19_SUBWAY/SUBWAY04", "SUBWAY04.MSH", "SUBWAY04.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0021"] = new[]
                {
                    new MapobjGroup("SALOON/LABA/1", "LABA1.MSH", "LABA1.HRC", "LABA1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/2", "LABA2.MSH", "LABA2.HRC", "LABA2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/3", "LABA3.MSH", "LABA3.HRC", "LABA3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/4", "LABA4.MSH", "LABA4.HRC", "LABA4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/5", "LABA5.MSH", "LABA5.HRC", "LABA5.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/6", "LABA6.MSH", "LABA6.HRC", "LABA6.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/7", "LABA7.MSH", "LABA7.HRC", "LABA7.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/8", "LABA8.MSH", "LABA8.HRC", "LABA8.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/9", "LABA9.MSH", "LABA9.HRC", "LABA9.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/10", "LABA10.MSH", "LABA10.HRC", "LABA10.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/11", "LABA11.MSH", "LABA11.HRC", "LABA11.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/LABA/12", "LABA12.MSH", "LABA12.HRC", "LABA12.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/1", "DENG1.MSH", "DENG1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/2", "DENG2.MSH", "DENG2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/3", "DENG3.MSH", "DENG3.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/4", "DENG4.MSH", "DENG4.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/5", "DENG5.MSH", "DENG5.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/6", "DENG6.MSH", "DENG6.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/7", "DENG7.MSH", "DENG7.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/8", "DENG8.MSH", "DENG8.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/9", "DENG9.MSH", "DENG9.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/10", "DENG10.MSH", "DENG10.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/11", "DENG11.MSH", "DENG11.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/DENG/12", "DENG12.MSH", "DENG12.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("SALOON/ZHUMEN", "ZHUMEN.MSH", "ZHUMEN.HRC", "ZHUMEN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0022"] = new[]
                {
                    new MapobjGroup("FENMU/DONG1", "GUANG4.MSH", "GUANG4.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/GUI", "LABA11.MSH", "LABA11.HRC", "LABA11.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/LANHUO", "SHAN.MSH", "SHAN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/GUI2", "LABA12.MSH", "LABA12.HRC", "LABA12.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/SHEGUANG", "SHEGUANG.MSH", "SHEGUANG.HRC", "SHEGUANG.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/SHEGUANG2", "SHEGUANG2.MSH", "SHEGUANG2.HRC", "SHEGUANG2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/SHEGUANG3", "SHEGUANG3.MSH", "SHEGUANG3.HRC", "SHEGUANG3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("FENMU/DONG2", "DONGHUA2.MSH", "DONGHUA2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0023"] = new[]
                {
                    new MapobjGroup("JIAOSHI/CHUANGHU", "CHUANGHU.MSH", "CHUANGHU.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/CHUANGHUFANSE", "CHUANGHUFANSE.MSH", "CHUANGHUFANSE.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA1", "LABA1.MSH", "LABA1.HRC", "LABA1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA2", "LABA2.MSH", "LABA2.HRC", "LABA2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA3", "LABA3.MSH", "LABA3.HRC", "LABA3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA4", "LABA4.MSH", "LABA4.HRC", "LABA4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA5", "LABA5.MSH", "LABA5.HRC", "LABA5.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA6", "LABA6.MSH", "LABA6.HRC", "LABA6.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA7", "LABA7.MSH", "LABA7.HRC", "LABA7.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA8", "LABA8.MSH", "LABA8.HRC", "LABA8.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA9", "LABA9.MSH", "LABA9.HRC", "LABA9.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIAOSHI/LABA10", "LABA10.MSH", "LABA10.HRC", "LABA10.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0024"] = new[]
                {
                    new MapobjGroup("XUEJING/DONGHUA", "DONGHUA.MSH", "DONGHUA.HRC", "DONGHUA.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("XUEJING/BIAODONGHUA", "BIAODONGHUA.MSH", "BIAODONGHUA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0025"] = new[]
                {
                    new MapobjGroup("CHUNTIAN/DONGHUA", "CHUNTIANDONGHUA.MSH", "CHUNTIANDONGHUA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CHUNTIAN/HUTEIDONGHUA", "HUDEICHUNTIANDONGHUA.MSH", "HUDEICHUNTIANDONGHUA.HRC", "HUDEICHUNTIANDONGHUA.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CHUNTIAN/HUDIEDONGHUA2", "HUDEICHUNTIANDONGHUA2.MSH", "HUDEICHUNTIANDONGHUA2.HRC", "HUDEICHUNTIANDONGHUA2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CHUNTIAN/HUDIEDONGHUA3", "HUDEICHUNTIANDONGHUA3.MSH", "HUDEICHUNTIANDONGHUA3.HRC", "HUDEICHUNTIANDONGHUA3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CHUNTIAN/HUDIEDONGHUA4", "HUDEICHUNTIANDONGHUA4.MSH", "HUDEICHUNTIANDONGHUA4.HRC", "HUDEICHUNTIANDONGHUA4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("CHUNTIAN/CAODONGHUA", "CAOCHUNTIANDONGHUA.MSH", "CAOCHUNTIANDONGHUA.HRC", "CAOCHUNTIANDONGHUA.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0026"] = new[]
                {
                    new MapobjGroup("LANQIUCHANG/CHE1", "CHE1.MSH", "CHE1.HRC", "CHE1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/CHE2", "CHE2.MSH", "CHE2.HRC", "CHE2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/CHE3", "CHE3.MSH", "CHE3.HRC", "CHE3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/CHE4", "CHE4.MSH", "CHE4.HRC", "CHE4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/DENG1", "DENG1.MSH", "DENG1.HRC", "DENG1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/DENG2", "DENG2.MSH", "DENG2.HRC", "DENG2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/DENG3", "DENG3.MSH", "DENG3.HRC", "DENG3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/HUO", "HUO.MSH", "HUO.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/LABA1", "LABA1.MSH", "LABA1.HRC", "LABA1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/LABA2", "LABA2.MSH", "LABA2.HRC", "LABA2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/LABA3", "LABA3.MSH", "LABA3.HRC", "LABA3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/LABA4", "LABA4.MSH", "LABA4.HRC", "LABA4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("LANQIUCHANG/XIAODENG", "XIAODENG.MSH", "XIAODENG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0028"] = new[]
                {
                    new MapobjGroup("NIAOCHAO/CHUAN", "CHUAN.MSH", "CHUAN.HRC", "CHUAN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("NIAOCHAO/DENG1", "DENG1_.MSH", "DENG1_.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("NIAOCHAO/DENG2", "DENG2_.MSH", "DENG2_.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("NIAOCHAO/DENG3", "DENG3_.MSH", "DENG3_.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("NIAOCHAO/DENG4", "DENG4_.MSH", "DENG4_.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("NIAOCHAO/FEICHUAN", "FEICHUAN.MSH", "FEICHUAN.HRC", "FEICHUAN.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("NIAOCHAO/PENGSHUI", "PENGSHUI_.MSH", "PENGSHUI_.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0029"] = new[]
                {
                    new MapobjGroup("JIKU/JIUBA", "JIUBA.MSH", "JIUBA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("JIKU/PINGMU", "PINGMU.MSH", "PINGMU.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCN0030"] = new[]
                {
                    new MapobjGroup("KATONGGONGLU/FENGCHEDONGHUA", "KONGTONGFENGCHE.MSH", "KONGTONGFENGCHE.HRC", "KONGTONGFENGCHE.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["MERRYROOMA"] = new[]
                {
                    new MapobjGroup("MERRYROOMA/HUNLI_A", "HUNLIA.MSH", "HUNLIA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["MERRYROOMB"] = new[]
                {
                    new MapobjGroup("MERRYROOMB/HUNLI_B", "HUNLIB.MSH", "HUNLIB.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("MERRYROOMB/HUNLI_BHUA", "HUNLIBHUA.MSH", "HUNLIBHUA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["MERRYROOMC"] = new[]
                {
                    new MapobjGroup("MERRYROOMC/HUNLI_C", "HUNLIC.MSH", "HUNLIC.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("MERRYROOMC/HUNLI_CHUA", "HUNLICHUA.MSH", "HUNLICHUA.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCNMYHOUSE"] = new[]
                {
                    new MapobjGroup("3DHOUSE/COUMPUTER", "COMPUTER.MSH", "COMPUTER.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCNROOM"] = new[]
                {
                    new MapobjGroup("ROOM_OBJ/DIANSHI", "TVDH.MSH", "TVDH.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA1", "LABADH1.MSH", "LABADH1.HRC", "LABADH1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA2", "LABADH2.MSH", "LABADH2.HRC", "LABADH2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA3", "LABADH3.MSH", "LABADH3.HRC", "LABADH3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA4", "LABADH4.MSH", "LABADH4.HRC", "LABADH4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG1", "GUANG1.MSH", "GUANG1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG2", "GUANG2.MSH", "GUANG2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG3", "GUANG3.MSH", "GUANG3.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG4", "GUANG4.MSH", "GUANG4.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG5", "GUANG5.MSH", "GUANG5.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG6", "GUANG6.MSH", "GUANG6.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG7", "GUANG7.MSH", "GUANG7.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG8", "GUANG8.MSH", "GUANG8.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/TAIZI", "TAIZI.MSH", "TAIZI.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCNMERRYROOM"] = new[]
                {
                    new MapobjGroup("ROOM_OBJ/DIANSHI", "TVDH.MSH", "TVDH.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA1", "LABADH1.MSH", "LABADH1.HRC", "LABADH1.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA2", "LABADH2.MSH", "LABADH2.HRC", "LABADH2.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA3", "LABADH3.MSH", "LABADH3.HRC", "LABADH3.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/LABA4", "LABADH4.MSH", "LABADH4.HRC", "LABADH4.MOT", new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG1", "GUANG1.MSH", "GUANG1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG2", "GUANG2.MSH", "GUANG2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG3", "GUANG3.MSH", "GUANG3.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG4", "GUANG4.MSH", "GUANG4.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG5", "GUANG5.MSH", "GUANG5.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG6", "GUANG6.MSH", "GUANG6.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG7", "GUANG7.MSH", "GUANG7.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_OBJ/GUANG8", "GUANG8.MSH", "GUANG8.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
                ["SCNROOM_NIGHT"] = new[]
                {
                    new MapobjGroup("ROOM_NIGHT_OBJ/LANG", "ROOM_SCENE.MSH", "ROOM_SCENE.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_NIGHT_OBJ/TANG1", "TANG1.MSH", "TANG1.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_NIGHT_OBJ/TANG2", "TANG2.MSH", "TANG2.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_NIGHT_OBJ/XIN", "XIN.MSH", "XIN.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                    new MapobjGroup("ROOM_NIGHT_OBJ/DENG", "DENG.MSH", "DENG.HRC", null, new[]
                    {
                        new MapobjPlacement(0f, 0f, 0f, 1f),
                    }),
                },
            };
        }
    }
}
