#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the four UI localization tables from a single source dict.

Writes StreamingAssets/Localization/{en,zh-TW,zh-Hans,ja}.json in the JsonUtility
array schema:  { "language","name","culture","entries":[{"k","v"},...] }

Keeping one source guarantees all languages share the exact same key set
(LocalizationTests.AllLanguages_HaveSameKeySet relies on this).
"""
import json, os

LANGS = [
    ("en",      "English",  "en-US"),
    ("zh-TW",   "繁體中文", "zh-TW"),
    ("zh-Hans", "简体中文", "zh-CN"),
    ("ja",      "日本語",   "ja-JP"),
]
ORDER = ["en", "zh-TW", "zh-Hans", "ja"]

# key: [en, zh-TW, zh-Hans, ja]
STR = {
    "common.apply":   ["Apply", "套用", "应用", "適用"],
    "common.back":    ["Back", "返回", "返回", "戻る"],
    "common.cancel":  ["Cancel", "取消", "取消", "キャンセル"],
    "common.close":   ["Close", "關閉", "关闭", "閉じる"],
    "common.confirm": ["Confirm", "確定", "确定", "確定"],
    "common.off":     ["Off", "關", "关", "オフ"],
    "common.on":      ["On", "開", "开", "オン"],
    "common.enabled":  ["On", "開啟", "开启", "オン"],
    "common.disabled": ["Off", "關閉", "关闭", "オフ"],

    "app.title": ["Dance Online", "熱舞 Online", "热舞 Online", "ダンス Online"],

    "lobby.create_room":    ["Create Room", "建立房間", "创建房间", "ルーム作成"],
    "lobby.rooms":          ["Rooms", "房間列表", "房间列表", "ルーム一覧"],
    "lobby.online_players": ["Online Players", "線上玩家", "在线玩家", "オンラインプレイヤー"],
    "lobby.chat":           ["Chat", "聊天", "聊天", "チャット"],
    "lobby.send":           ["Send", "送出", "发送", "送信"],
    "lobby.settings":       ["Settings", "設定", "设置", "設定"],
    "lobby.logout":         ["Logout", "登出", "登出", "ログアウト"],
    "lobby.select_note":    ["Notes", "選擇音符", "选择音符", "ノーツ選択"],
    "lobby.empty":          ["No rooms yet — create one!", "目前沒有房間，來建立一間吧！", "目前没有房间，来建一个吧！", "ルームがありません。作成しましょう！"],
    "lobby.col_room":       ["Room", "房號", "房号", "番号"],
    "lobby.col_host":       ["Host", "房主", "房主", "ホスト"],
    "lobby.col_count":      ["Players", "人數", "人数", "人数"],
    "lobby.col_mode":       ["Mode", "模式", "模式", "モード"],
    "lobby.col_status":     ["Status", "狀態", "状态", "状態"],
    # 官方版位的大廳（DDRLOBBY）：右下角自己的角色資料，以及「快速進入」的兩種結果。
    "lobby.record":         ["{0}W {1}L", "{0} 勝 {1} 敗", "{0} 胜 {1} 负", "{0}勝 {1}敗"],
    "lobby.no_quick_room":  ["No open stage to join right now", "現在沒有可以加入的等待中舞台",
                             "现在没有可以加入的等待中舞台", "今すぐ入れる待機中のステージがありません"],
    "lobby.joined_as_spectator": ["Seats are full — joining as a spectator", "座位已滿，以旁觀身分進入",
                                  "座位已满，以旁观身份进入", "座席が満員のため、観戦として参加します"],

    # 玩家名單（官方 win3：全部 / 好友 / 家族 / 黑名單）。
    "lobby.userlist_in_lobby":   ["Lobby", "大廳", "大厅", "ロビー"],
    "lobby.userlist_in_room":    ["Room {0}", "{0} 號房", "{0} 号房", "ルーム {0}"],

    "room.title":           ["Room {0}", "房間 {0}", "房间 {0}", "ルーム {0}"],
    "room.server_name":     ["Free Practice {0}", "自由練習場{0}", "自由练习场{0}", "自由練習場{0}"],
    "room.channel":         ["ch{0}", "頻道{0}", "频道{0}", "ch{0}"],
    "room.default_name":    ["{0}'s Dance Room", "{0}的舞蹈室", "{0}的舞蹈室", "{0}のダンスルーム"],
    "room.leave":           ["Leave Room", "離開房間", "离开房间", "ルーム退出"],
    "room.ready":           ["Ready", "準備", "准备", "準備"],
    "room.cancel_ready":    ["Cancel", "取消準備", "取消准备", "準備解除"],
    "room.start":           ["Start", "開始", "开始", "開始"],
    "room.select_song":     ["Select Song", "選擇歌曲", "选择歌曲", "曲を選択"],
    "room.no_song":         ["(No song selected)", "（尚未選歌）", "（尚未选歌）", "（曲未選択）"],
    "room.mode":            ["Mode", "模式", "模式", "モード"],
    # 創建房間對話框的「遊戲模式」——官方那格是固定值（不是下拉），照官方寫死。
    "room.mode_fashion":    ["Fashion Dance", "時尚超舞", "时尚超舞", "ファッションダンス"],
    "room.empty_seat":      ["Empty", "空位", "空位", "空席"],
    "room.host":            ["Host", "房主", "房主", "ホスト"],
    "room.waiting_players": ["Some players are not ready", "尚有玩家未準備", "还有玩家未准备", "未準備のプレイヤーがいます"],
    "room.need_song":       ["Please select a song first", "請先選擇歌曲", "请先选择歌曲", "先に曲を選択してください"],
    # 加入房間流程(選男女畫面的「加入房間」→ 房號輸入框)
    "room.join_title":           ["Join Room", "房號輸入", "房号输入", "ルーム番号入力"],
    "room.join_code":            ["Code", "房號", "房号", "番号"],
    "room.join_confirm":         ["OK", "確認", "确认", "確認"],
    "room.join_bad_code":        ["Enter a 5-digit room code", "房號是 5 位數字", "房号是 5 位数字", "ルーム番号は5桁です"],
    "room.join_not_found":       ["No room with that code", "找不到這個房號", "找不到这个房号", "そのルームは見つかりません"],
    "room.join_full":            ["That room is full", "房間已滿", "房间已满", "ルームが満員です"],
    "room.join_in_game":         ["That room is in a match", "這間房正在遊戲中", "这间房正在游戏中", "対戦中のルームです"],
    "room.join_failed":          ["Could not join the room", "加入房間失敗", "加入房间失败", "ルームに参加できませんでした"],
    "room.create_failed":        ["Failed to create room", "建立房間失敗", "创建房间失败", "ルームの作成に失敗しました"],
    # M3 座位操作(房主右鍵選單 / 雙擊鎖格)與組隊
    "room.slot_kick":          ["Kick player", "踢出玩家", "踢出玩家", "プレイヤーをキック"],
    "room.kicked":             ["You were removed from the room", "你被請出了房間", "你被请出了房间", "部屋から退出させられました"],
    # M4 同步進場
    "room.force_start_hint":   ["Not everyone is ready — press Start again to force",
                                "尚有玩家未準備 — 再按一次「開始」強制開始",
                                "还有玩家未准备 — 再按一次「开始」强制开始",
                                "未準備のプレイヤーがいます — もう一度「開始」で強制スタート"],
    "room.start_no_response":  ["The server did not respond to the start request",
                                "伺服器沒有回應開始請求", "服务器没有回应开始请求", "サーバーが開始要求に応答しませんでした"],
    "room.match_aborted":      ["The round was cancelled", "這一局被取消了", "这一局被取消了", "このラウンドは中止されました"],
    # 「切換房主」而不是「交出房主」：房主可以把房主給任何一個座位上的人，之後也能再換一次 ——
    # 「交出」聽起來像一去不回的單向動作，而它其實只是換人當。
    "room.slot_transfer_host": ["Transfer host", "切換房主", "切换房主", "ホストを変更"],
    "room.slot_close":         ["Close seat", "關閉位置", "关闭位置", "席を閉じる"],
    "room.slot_open":          ["Open seat", "開啟位置", "开启位置", "席を開く"],
    # 右鍵選單的社交組（官方 PopMenu 那三項）。管理組（切換房主/踢出/開關位置）在上面。
    "room.slot_player_info":   ["Player info", "玩家信息", "玩家信息", "プレイヤー情報"],
    "room.slot_whisper":       ["Whisper", "私聊", "私聊", "ささやく"],
    "room.slot_add_friend":    ["Add friend", "加為好友", "加为好友", "フレンド追加"],
    "room.slot_remove_friend": ["Remove friend", "刪除好友", "删除好友", "フレンド削除"],
    # 黑名單（PlayerMenuLabels）—— 這兩個 key 一直沒定義，選單上看到的是 [room.slot_block]。
    "room.slot_block":         ["Block", "加入黑名單", "加入黑名单", "ブロック"],
    "room.slot_unblock":       ["Unblock", "移出黑名單", "移出黑名单", "ブロック解除"],
    "room.friend_added":       ["Added {0} to your friends", "已將 {0} 加為好友",
                                "已将 {0} 加为好友", "{0} をフレンドに追加しました"],
    "room.friend_add_failed":  ["Could not add {0} to your friends", "無法將 {0} 加為好友",
                                "无法将 {0} 加为好友", "{0} をフレンドに追加できませんでした"],
    "room.friend_removed":     ["Removed {0} from your friends", "已將 {0} 從好友清單移除",
                                "已将 {0} 从好友列表移除", "{0} をフレンドから削除しました"],
    "room.friend_remove_failed": ["{0} is not in your friends list", "好友清單裡沒有 {0}",
                                  "好友列表里没有 {0}", "{0} はフレンドに登録されていません"],

    # 玩家資訊視窗（官方 PlayerInformationDlg）。
    "room.info_name":          ["Name", "名稱", "名称", "名前"],
    "room.info_gender":        ["Gender", "性別", "性别", "性別"],
    "room.info_gender_male":   ["Male", "男", "男", "男性"],
    "room.info_gender_female": ["Female", "女", "女", "女性"],
    "room.info_family":        ["Family", "家族", "家族", "ファミリー"],
    "room.info_level":         ["Level", "等級", "等级", "レベル"],
    "room.info_none":          ["(none)", "(無)", "(无)", "(なし)"],
    "room.info_coins":         ["M coins", "M幣", "M币", "Mコイン"],
    "room.info_points":        ["G coins", "G幣", "G币", "Gコイン"],
    "room.info_bonus":         ["P coins", "P幣", "P币", "Pコイン"],
    "room.info_accuracy":      ["Accuracy", "命中率", "命中率", "命中率"],
    "room.info_perfect":       ["Perfect", "Perfect率", "Perfect率", "Perfect率"],
    "room.info_cool":          ["Cool", "Cool率", "Cool率", "Cool率"],
    "room.info_bad":           ["Bad", "Bad率", "Bad率", "Bad率"],
    "room.info_miss":          ["Miss", "Miss率", "Miss率", "Miss率"],
    "room.info_winrate":       ["Win rate", "勝率", "胜率", "勝率"],
    "room.info_judged":        ["Judgements", "判定數", "判定数", "判定数"],
    "room.info_judged_value":  ["P {0} / C {1} / B {2} / M {3}", "P {0} / C {1} / B {2} / M {3}",
                                "P {0} / C {1} / B {2} / M {3}", "P {0} / C {1} / B {2} / M {3}"],
    "room.info_plays":         ["Songs played", "遊玩次數", "游玩次数", "プレイ回数"],
    "room.info_plays_value":   ["{0}", "{0} 次", "{0} 次", "{0} 回"],
    "room.info_record":        ["Record", "戰績", "战绩", "戦績"],
    "room.info_record_value":  ["{0}W {1}L", "{0} 勝 {1} 負", "{0} 胜 {1} 负", "{0} 勝 {1} 敗"],
    "room.info_no_stats":      ["No records yet — finish a song and the totals start counting.",
                                "還沒有紀錄 —— 完整打完一首歌就會開始累計。",
                                "还没有记录 —— 完整打完一首歌就会开始累计。",
                                "まだ記録がありません — 1曲を最後までプレイすると集計が始まります。"],
    # 這句是「名片還沒到」時的替代文字（見 PlayerInfoModal.ApplyRemoteCard：名片一到就把它收掉）。
    # 以前它寫的是「伺服器不保存玩家統計」——那在 setCard/cardQuery 之後已經不成立了，
    # 現在說的是真正的兩個原因：對方離線，或對方跑的是還不會上傳名片的舊版。
    "room.info_remote_stats":  ["This player's record hasn't arrived - they may be offline, or running an older build that doesn't publish it.",
                                "對方的資料還沒送到 —— 可能已經離線，或還在用不會上傳資料的舊版。",
                                "对方的资料还没送到 —— 可能已经离线，或还在用不会上传资料的旧版。",
                                "相手のデータがまだ届いていません — オフラインか、データを送信しない旧バージョンの可能性があります。"],
    "room.info_remote_basic":  ["Only the name, family and level travel over the network — nothing else is stored on the server.",
                                "線上只帶得到名字、家族與等級，其餘資料伺服器沒有保存。",
                                "线上只带得到名字、家族与等级，其余资料服务器没有保存。",
                                "オンラインで取得できるのは名前・ファミリー・レベルだけで、それ以外はサーバーに保存されていません。"],
    "room.teams_2v2":          ["Teams 2v2", "分隊 2對2", "分队 2对2", "チーム 2対2"],
    "room.teams_3v3":          ["Teams 3v3", "分隊 3對3", "分队 3对3", "チーム 3対3"],
    "room.teams_2v2v2":       ["Teams 2v2v2", "分隊 2對2對2", "分队 2对2对2", "チーム 2対2対2"],
    "room.teams_need_layout":  ["Team sizes must be 2v2, 3v3 or 2v2v2",
                                "組隊人數必須是 2對2、3對3 或 2對2對2",
                                "组队人数必须是 2对2、3对3 或 2对2对2",
                                "チーム人数は 2対2 / 3対3 / 2対2対2 のいずれかにしてください"],
    "room.teams_assigned":     ["Teams assigned", "已自動分隊", "已自动分队", "チームを割り当てました"],
    # M7 旁觀(需求 10)。三道門各一句 —— 靜默失敗的話玩家只會覺得「按了沒反應」。
    "room.spectate_offline":   ["Spectating needs a server connection", "旁觀需要連上伺服器",
                                "旁观需要连上服务器", "観戦にはサーバー接続が必要です"],
    "room.spectate_in_match":  ["You are in this round — you cannot switch to spectating",
                                "你正在這一局裡 — 不能切成旁觀",
                                "你正在这一局里 — 不能切成旁观",
                                "このラウンドに参加中です — 観戦に切り替えられません"],
    "room.spectate_ready":     ["Cancel your ready first", "請先取消準備", "请先取消准备",
                                "先に準備を解除してください"],
    "room.spectate_no_host":   ["No one can take over as host", "沒有人能接手房主", "没有人能接手房主",
                                "ホストを引き継げる人がいません"],
    "room.spectate_on":        ["Spectating — your seat is released", "旁觀中 — 座位已釋出",
                                "旁观中 — 座位已释出", "観戦中 — 席を手放しました"],
    # server 回的 error{code}。**沒有這些字的時候玩家只會覺得「按了沒反應」** ——
    # 這些錯誤原本沒有任何訂閱者,整個被丟掉。
    "neterr.not_host":         ["Only the host can do that", "只有房主可以做這件事",
                                "只有房主可以做这件事", "ホストのみ可能です"],
    "neterr.not_in_room":      ["You are not in a room", "你不在房間裡", "你不在房间里", "ルームにいません"],
    "neterr.bad_seat":         ["That seat cannot be changed", "這個位置不能這樣操作",
                                "这个位置不能这样操作", "その席は変更できません"],
    "neterr.bad_state":        ["Not possible right now", "現在不能做這件事",
                                "现在不能做这件事", "今はできません"],
    "neterr.no_song":          ["The room has no song selected", "房間還沒選歌",
                                "房间还没选歌", "曲が選ばれていません"],
    "neterr.full":             ["No free seat", "沒有空的座位", "没有空的座位", "空席がありません"],
    "neterr.looker_full":      ["The spectator slots are full", "旁觀席已經滿了",
                                "旁观席已经满了", "観戦枠が満員です"],
    # server 不認得 client 送的訊息 = 兩邊版本不一樣。靜默的話症狀是「訊息憑空消失」,查不出原因。
    "neterr.proto":            ["Server version mismatch — please update", "伺服器版本不符,請更新",
                                "服务器版本不符,请更新", "サーバーのバージョンが違います"],
    # 自由模式按組隊時的提示。這個 key 以前沒定義 → 畫面直接顯示 [room.teams_normal_mode_only]。
    "room.teams_normal_mode_only": ["Teams are for Normal mode only", "只有普通模式可以組隊",
                                "只有普通模式可以组队", "チーム戦はノーマルのみ"],
    # 建房失敗:server 的房間數到上限。原本直接把 server 回的英文代碼(full)貼在畫面上。
    "room.create_failed_full": ["The server has no room slots left", "伺服器的房間已經滿了",
                                "服务器的房间已经满了", "サーバーの部屋が満杯です"],
    # (開機連不上 → 退回單機:刻意不告訴玩家。沒填 serverAddress / 伺服器沒開的人本來就是
    #  要單機玩的,那句話對他沒有用;技術原因寫進 log 就好。見 Toast.cs 開頭那條線。)
    # 同名被擋(server 只讓先上線的那個留著)。這句與上面那條線的差別在「玩家能不能處理」:
    # 連不上他多半只能去查網路(所以不說),但名字被占用時伺服器明明連得上,改個名字就好 —— 要說。
    "net.name_taken":          ["Login failed — that name is already in use", "登入失敗：這個名稱已被使用",
                                "登录失败：这个名称已被使用", "ログイン失敗：その名前は使用中です"],
    # 連上之後**中途**斷線(server 關掉、網路斷了)。這句與「開機連不上」相反 —— 那個不說,
    # 但這個玩家已經在線上了,畫面突然變單機又被帶回登入頁,不說一句他只會覺得壞了。
    "net.link_lost":           ["Disconnected from the server", "與伺服器的連線中斷",
                                "与服务器的连接中断", "サーバーとの接続が切れました"],
    # 傳歌失敗。原本把內部錯誤字串接在後面,玩家看不懂也不能做什麼。
    "net.transfer_failed":     ["Song transfer failed — please try again", "歌曲傳輸失敗,請稍後再試",
                                "歌曲传输失败,请稍后再试", "曲の転送に失敗しました"],
    # 同一件事但**程式會自己再試一次**(線路問題、還沒用完重試次數 —— 見 NetSongTransfer.MaxDownloadRetries)。
    # 與上面那句分開是因為玩家該做的事相反:這句要他「等一下」,那句要他「自己再試」。
    "net.transfer_retry":      ["Song transfer failed — retrying", "歌曲傳輸失敗,正在重試",
                                "歌曲传输失败,正在重试", "曲の転送に失敗しました — 再試行中"],
    "settings.applied":        ["Settings applied", "設定已套用", "设置已套用", "設定を適用しました"],
    "room.spectate_off":       ["Back in a seat", "已回到座位", "已回到座位", "席に戻りました"],
    "room.drop_up":         ["Up", "向上", "向上", "上"],
    "room.drop_down":       ["Down", "向下", "向下", "下"],
    "room.drop_tilt":       ["Tilt", "傾斜", "倾斜", "斜め"],

    # 密語（私聊）與進出舞台廣播 —— 左下訊息欄
    "room.whisper_out":        ["You whisper to {0}: {1}", "你對{0}說: {1}", "你对{0}说: {1}", "{0}にささやく: {1}"],
    "room.whisper_in":         ["{0} whispers to you: {1}", "{0}對你說: {1}", "{0}对你说: {1}", "{0}があなたにささやく: {1}"],
    "room.whisper_offchannel": ["{0} is not in this channel", "{0}不在當前頻道", "{0}不在当前频道", "{0}は現在のチャンネルにいません"],
    "room.whisper_noid":       ["Player {0} not found", "找不到玩家 {0}", "找不到玩家 {0}", "{0} というプレイヤーが見つかりません"],
    # 進出成對出現,所以句型要**一模一樣**(名字 + 一個半形空格 + 動作 + 舞台遊戲)——
    # 原本進場有空格、離場沒有,而且一個寫「舞台遊戲」一個寫「舞台」,兩行疊在訊息欄裡看起來像兩套東西。
    "room.stage_enter":        ["{0} entered the stage", "{0} 進入舞台遊戲", "{0} 进入舞台游戏", "{0} がステージに入りました"],
    "room.stage_leave":        ["{0} left the stage", "{0} 離開舞台遊戲", "{0} 离开舞台游戏", "{0} がステージから退場しました"],

    # 好友頻道沒帶對象 → 你說(白) / 家族頻道 → /家族 前綴 + <家族> 綠字 + 你沒有家族(紅)
    "room.selftalk":           ["You say: {0}", "你說: {0}", "你说: {0}", "あなた: {0}"],
    "room.no_guild":           ["You have no guild", "你沒有家族", "你没有家族", "ギルドに所属していません"],
    "room.guild_command":      ["guild", "家族", "家族", "ギルド"],
    "room.guild_tag":          ["<Guild>", "<家族>", "<家族>", "<ギルド>"],
    "room.debug_guild":        ["[Debug] Guild: {0}", "[除錯] 家族: {0}", "[调试] 家族: {0}", "[デバッグ] ギルド: {0}"],
    "room.debug_guild_none":   ["(none)", "（無）", "（无）", "（なし）"],

    "result.clear":     ["Clear!", "完成!", "完成!", "クリア!"],
    "result.failed":    ["Failed", "失敗", "失败", "失敗"],
    "result.score":     ["Score", "分數", "分数", "スコア"],
    "result.max_combo": ["Max Combo", "最大連段", "最大连段", "最大コンボ"],
    "result.back":      ["Back to Room", "返回房間", "返回房间", "ルームに戻る"],

    "mode.free":   ["Free", "自由", "自由", "フリー"],
    "mode.normal": ["Normal", "普通", "普通", "ノーマル"],

    "status.waiting": ["Waiting", "等待中", "等待中", "待機中"],
    "status.ingame":  ["In Game", "遊戲中", "游戏中", "ゲーム中"],

    "songselect.title":     ["Select Song", "選擇歌曲", "选择歌曲", "曲を選択"],
    "songselect.random":    ["Random", "隨機場景", "随机场景", "ランダム"],
    "songselect.stage":     ["Stage", "舞台", "舞台", "ステージ"],
    "songselect.search":    ["Type a keyword and press Enter", "輸入關鍵字並送出", "输入关键字并回车", "キーワードを入力してEnter"],
    "songselect.bpm":       ["BPM {0}", "BPM {0}", "BPM {0}", "BPM {0}"],
    "songselect.level":     ["Lv {0}", "Lv {0}", "Lv {0}", "Lv {0}"],
    "songselect.page":      ["Page {0}/{1}", "第 {0}/{1} 頁", "第 {0}/{1} 页", "{0}/{1} ページ"],
    "songselect.prev":      ["Prev", "上一頁", "上一页", "前へ"],
    "songselect.next":      ["Next", "下一頁", "下一页", "次へ"],
    "songselect.no_songs":  ["No songs found", "找不到歌曲", "找不到歌曲", "曲が見つかりません"],
    "songselect.confirm":   ["Confirm", "選定", "选定", "決定"],
    "songselect.need_pick": ["Please pick a song first", "請先選擇歌曲", "请先选择歌曲", "先に曲を選んでください"],
    # NOTE: 場景選擇 caption + 演唱者/BPM info labels are BAKED into MUSICSELDLG art (and 音符數 uses lbl_notes.an),
    # so they are NOT text-localized here — the song-select screen draws values only. See SongSelectScreen.cs.
    "songselect.mode_free":     ["Free Mode", "自由模式", "自由模式", "フリーモード"],
    "songselect.mode_normal":   ["Normal Mode", "普通模式", "普通模式", "ノーマルモード"],
    "songselect.mode_showtime": ["ShowTime", "ShowTime", "ShowTime", "ShowTime"],
    "songselect.form_basic":  ["Basic", "基本", "基本", "基本"],
    "songselect.form_fan":    ["Fan", "扇形", "扇形", "扇形"],
    "songselect.form_ring":   ["Ring", "環繞", "环绕", "リング"],
    "songselect.form_random": ["Random", "隨機", "随机", "ランダム"],

    # 隨機 tab difficulty-range rows
    "songselect.rand_1_5":  ["Random Lv 1-5",  "隨機難度 1-5",    "随机难度 1-5",    "ランダム難易度 1-5"],
    "songselect.rand_1_9":  ["Random Lv 1-9",  "隨機難度 1-9",    "随机难度 1-9",    "ランダム難易度 1-9"],
    "songselect.rand_5_9":  ["Random Lv 5-9",  "隨機難度 5-9",    "随机难度 5-9",    "ランダム難易度 5-9"],
    "songselect.rand_all":  ["Random Lv All",  "隨機難度 全部",   "随机难度 全部",   "ランダム難易度 全部"],
    "songselect.rand_5up":  ["Random Lv 5+",   "隨機難度 5級以上",  "随机难度 5级以上",  "ランダム難易度 5以上"],
    "songselect.rand_9up":  ["Random Lv 9+",   "隨機難度 9級以上",  "随机难度 9级以上",  "ランダム難易度 9以上"],
    "songselect.rand_13up": ["Random Lv 13+",  "隨機難度 13級以上", "随机难度 13级以上", "ランダム難易度 13以上"],
    "songselect.rand_20up": ["Random Lv 20+",  "隨機難度 20級以上", "随机难度 20级以上", "ランダム難易度 20以上"],
    "songselect.rand_25up": ["Random Lv 25+",  "隨機難度 25級以上", "随机难度 25级以上", "ランダム難易度 25以上"],

    # 分類瀏覽 — the floating group panel behind the 資料夾 category (StepMania-style sections)
    "songselect.group_panel":  ["Browse", "分類瀏覽", "分类浏览", "カテゴリ"],
    # the panel's grouping tabs are English in every language (they sit in a narrow toolbar; asked for verbatim)
    "songselect.group_folder": ["Group", "Group", "Group", "Group"],
    "songselect.group_title":  ["Song", "Song", "Song", "Song"],
    "songselect.group_artist": ["Artist", "Artist", "Artist", "Artist"],
    "songselect.group_bpm":    ["BPM", "BPM", "BPM", "BPM"],
    "songselect.group_other":  ["Other", "其他", "其他", "その他"],
    "songselect.group_uncat":  ["(Ungrouped)", "(未分類)", "(未分类)", "(未分類)"],
    "songselect.group_bpm_unknown": ["BPM ?", "BPM 未知", "BPM 未知", "BPM 不明"],
    "songselect.group_empty":  ["No songs in Songs/", "Songs/ 裡沒有歌曲", "Songs/ 里没有歌曲", "Songs/ に曲がありません"],
    # 分類瀏覽面板底部的「更新」鈕（重掃外部歌資料夾）與掃描狀態/結果訊息
    "songselect.group_refresh":         ["Refresh", "更新", "更新", "更新"],
    "songselect.group_scanning":        ["Scanning…", "掃描中…", "扫描中…", "スキャン中…"],
    "songselect.group_refresh_done":    ["Songs updated: {0}", "歌曲已更新：{0}", "歌曲已更新：{0}", "曲を更新：{0}"],
    "songselect.group_refresh_none":    ["No changes ({0} songs)", "歌曲沒有變更（共 {0} 首）", "歌曲没有变更（共 {0} 首）", "変更なし（全 {0} 曲）"],
    "songselect.group_refresh_added":   ["{0} added", "新增 {0} 首", "新增 {0} 首", "{0} 曲追加"],
    "songselect.group_refresh_changed": ["{0} changed", "更新 {0} 首", "更新 {0} 首", "{0} 曲更新"],
    "songselect.group_refresh_removed": ["{0} removed", "移除 {0} 首", "移除 {0} 首", "{0} 曲削除"],
    "songselect.group_refresh_sep":     [", ", "、", "、", "、"],

    # 3D stage names — selector scenes (ids 0..30) + special rooms (31/32/33/35/37/38/39).
    # zh-TW are the real EXE names; en/ja are translations (proper nouns like NARNIA kept as-is).
    "stage.name.0":  ["Pedestrian Street", "步行街", "步行街", "歩行者天国"],
    "stage.name.1":  ["New World", "新天地", "新天地", "新天地"],
    "stage.name.2":  ["Garage", "車庫", "车库", "ガレージ"],
    "stage.name.3":  ["Stage", "舞台", "舞台", "ステージ"],
    "stage.name.4":  ["Beach", "海灘", "海滩", "ビーチ"],
    "stage.name.5":  ["Christmas Eve", "聖誕夜", "圣诞夜", "クリスマスイブ"],
    "stage.name.6":  ["Amusement Park", "遊樂場", "游乐场", "遊園地"],
    "stage.name.7":  ["Polar Garden", "極地花園", "极地花园", "極地の花園"],
    "stage.name.8":  ["Egyptian Tomb", "埃及古墓", "埃及古墓", "エジプトの墓"],
    "stage.name.9":  ["Black & White Ball", "黑白舞會", "黑白舞会", "白黒の舞踏会"],
    "stage.name.10": ["Parade Float", "花車", "花车", "フロート"],
    "stage.name.11": ["Dance Grand Meet", "舞林大會", "舞林大会", "ダンス大会"],
    "stage.name.12": ["Soccer Field (Day)", "足球場 (日)", "足球场 (日)", "サッカー場（昼）"],
    "stage.name.13": ["Soccer Field (Night)", "足球場 (夜)", "足球场 (夜)", "サッカー場（夜）"],
    "stage.name.14": ["Seabed", "海底", "海底", "海底"],
    "stage.name.15": ["Magic House", "魔法屋", "魔法屋", "魔法の家"],
    "stage.name.16": ["Busy Street", "繁華街道", "繁华街道", "繁華街"],
    "stage.name.17": ["City Subway", "都市地鐵", "都市地铁", "都市の地下鉄"],
    "stage.name.18": ["Luxury Cruise", "豪華郵輪", "豪华邮轮", "豪華客船"],
    "stage.name.19": ["Dance Battle Arena", "舞鬥競技場", "舞斗竞技场", "ダンスバトル闘技場"],
    "stage.name.20": ["Subway Station", "地鐵驛站", "地铁驿站", "地下鉄駅"],
    "stage.name.21": ["Dance Bar", "激舞酒吧", "激舞酒吧", "ダンスバー"],
    "stage.name.22": ["Graveyard", "墓地", "墓地", "墓地"],
    "stage.name.23": ["Classroom", "教室", "教室", "教室"],
    "stage.name.24": ["Snowscape", "雪景", "雪景", "雪景色"],
    "stage.name.25": ["Spring", "春天", "春天", "春"],
    "stage.name.26": ["Basketball Court", "籃球場", "篮球场", "バスケットコート"],
    "stage.name.27": ["NARNIA", "NARNIA", "NARNIA", "NARNIA"],
    "stage.name.28": ["Beijing Night", "北京之夜", "北京之夜", "北京の夜"],
    "stage.name.29": ["Airport", "飛機場", "飞机场", "空港"],
    "stage.name.30": ["Cartoon Road", "卡通公路", "卡通公路", "カートゥーンロード"],
    "stage.name.31": ["Wedding Room A", "婚禮房 A", "婚礼房 A", "ウェディングルーム A"],
    "stage.name.32": ["Wedding Room B", "婚禮房 B", "婚礼房 B", "ウェディングルーム B"],
    "stage.name.33": ["Wedding Room C", "婚禮房 C", "婚礼房 C", "ウェディングルーム C"],
    "stage.name.35": ["My Home", "我的家", "我的家", "マイホーム"],
    "stage.name.37": ["Private Room", "個人房", "个人房", "個人ルーム"],
    "stage.name.38": ["Wedding Hall", "婚禮大廳", "婚礼大厅", "ウェディングホール"],
    "stage.name.39": ["Private Room (Night)", "個人房（夜）", "个人房（夜）", "個人ルーム（夜）"],

    # 自由模式的「難度設置」標題。官方圖 FMdif.an 把簡體字烘死在裡面,程式抹掉後疊這行翻譯上去
    # (見 RoomScreen.BuildFreeModeLevel)—— key 沒定義的話畫面上會直接看到 [room.difficulty_setting]。
    "room.difficulty_setting": ["Difficulty", "難度設置", "难度设置", "難易度設定"],
    "difficulty.easy":   ["Easy", "簡單", "简单", "かんたん"],
    "difficulty.normal": ["Normal", "普通", "普通", "ふつう"],
    "difficulty.hard":   ["Hard", "困難", "困难", "むずかしい"],

    "note.title": ["Select Notes", "選擇音符", "选择音符", "ノーツ選択"],

    "settings.title":        ["Settings", "設定", "设置", "設定"],
    "settings.tab.video":    ["Video", "畫面", "画面", "画面"],
    "settings.tab.audio":    ["Audio", "音效", "音效", "オーディオ"],
    "settings.tab.language": ["Language", "語言", "语言", "言語"],
    "settings.resolution":   ["Window Size", "視窗大小", "窗口大小", "ウィンドウサイズ"],
    "settings.display_mode": ["Display Mode", "顯示模式", "显示模式", "表示モード"],
    "settings.vsync":        ["VSync", "垂直同步", "垂直同步", "垂直同期"],
    "settings.bgm":          ["BGM Volume", "背景音樂", "背景音乐", "BGM 音量"],
    "settings.game_music":   ["Game Music", "遊戲音樂", "游戏音乐", "ゲーム音楽"],
    "settings.sfx":          ["SFX", "音效", "音效", "効果音"],
    "settings.language":     ["Language", "語言", "语言", "言語"],
    "settings.play_full_song": ["Full Play Mode", "完奏模式", "完奏模式", "完奏モード"],
    "settings.song_speed":     ["Song Speed", "歌曲變速", "歌曲变速", "曲の変速"],
    "settings.song_bomb":      ["Song Mines", "歌曲炸彈", "歌曲炸弹", "曲の爆弾"],

    "display.windowed":   ["Windowed", "視窗", "窗口", "ウィンドウ"],
    "display.fullscreen": ["Fullscreen", "全螢幕", "全屏", "フルスクリーン"],
    "display.borderless": ["Borderless", "無邊框全螢幕", "无边框全屏", "ボーダーレス"],

    # OPTION dialog (faithful OPTIONDLG rebuild; official pink frame + dynamic text)
    "option.title":        ["Options", "選項", "选项", "オプション"],
    "option.tab.video":    ["Display", "畫面", "画面", "画面"],
    "option.tab.audio":    ["Audio", "音效", "音效", "オーディオ"],
    "option.tab.keyboard": ["Keyboard", "鍵盤", "键盘", "キーボード"],
    "option.key.primary":  ["Primary Keys", "主鍵位", "主键位", "メインキー"],
    "option.key.aux":      ["Auxiliary", "輔助鍵位", "辅助键位", "補助キー"],
    "option.key.prompt":   ["Press any key…", "請按任意鍵…", "请按任意键…", "キーを押してください…"],
    "option.save":         ["Save", "儲存", "保存", "保存"],
    "option.exit":         ["Exit", "離開", "退出", "終了"],
    "option.default":      ["Default", "預設", "默认", "デフォルト"],
    # NOTE: the 遊戲 (OptionGameWindow) labels/captions + all four tab labels are BAKED into OPTIONDLG.clean.png,
    # so they are NOT localized here — only the 進階 (display) page draws text, reusing the settings.* keys above.

    "join.full":     ["This room is full", "這個房間已滿了", "这个房间已满了", "このルームは満員です"],
    "join.ingame":   ["This room is in game", "這個房間正在遊戲中", "这个房间正在游戏中", "このルームはゲーム中です"],
    "join.notfound": ["Room not found", "房間不存在", "房间不存在", "ルームが見つかりません"],
    # 開場（選性別）畫面左側那塊設定面板—— config.ini 裡「遊戲內沒有其它 UI 可以改」的設定全集。
    # 表在 StartupConfigSchema（cfg.<名字>.label / .help）、UI 在 StartupConfigPanel（cfg.panel.*）。
    # 新增一列設定就要在這裡補一組 label/help，否則 StartupConfigLocalizationTests 直接紅。
    "cfg.cat.net":                       ["Net", "連線", "连接", "接続"],
    "cfg.cat.play":                      ["Play", "遊玩", "游玩", "プレイ"],
    "cfg.cat.song":                      ["Songs", "歌曲", "歌曲", "曲"],
    "cfg.cat.text":                      ["Display", "顯示", "显示", "表示"],
    "cfg.cat.mmd":                       ["MMD", "MMD", "MMD", "MMD"],
    "cfg.panel.title":                   ["Player Settings", "玩家設定", "玩家设置", "プレイヤー設定"],
    "cfg.panel.title_collapsed":         ["Player Name", "玩家名稱", "玩家名称", "プレイヤー名"],
    "cfg.panel.expand":                  ["▼ More", "▼ 展開", "▼ 展开", "▼ 開く"],
    "cfg.panel.collapse":                ["▲ Less", "▲ 縮小", "▲ 缩小", "▲ 閉じる"],
    "cfg.panel.name":                    ["Name", "名稱", "名称", "名前"],
    "cfg.panel.save_name":               ["Save", "儲存", "保存", "保存"],
    "cfg.panel.save_config":             ["Save settings", "儲存設定", "保存设置", "設定を保存"],
    "cfg.panel.saved":                   ["Settings saved", "設定已儲存", "设置已保存", "設定を保存しました"],
    "cfg.panel.save_failed":             ["Save failed: {0}", "儲存失敗：{0}", "保存失败：{0}", "保存に失敗しました：{0}"],
    "cfg.panel.help_hint":               ["Hover a setting to see what it does.",
                                          "滑鼠移到設定上會顯示說明。",
                                          "鼠标移到设置上会显示说明。",
                                          "設定にマウスを合わせると説明が出ます。"],
    "cfg.panel.reveal":                  ["Show", "顯", "显", "表示"],
    "cfg.panel.hide":                    ["Hide", "隱", "隐", "隠す"],
    "cfg.panel.body":                    ["Build", "體型", "体型", "体型"],
    "cfg.panel.body.0":                  ["Slim", "瘦", "瘦", "細身"],
    "cfg.panel.body.1":                  ["Normal", "標準", "标准", "標準"],
    "cfg.panel.body.2":                  ["Chubby", "微胖", "微胖", "ぽっちゃり"],
    "cfg.panel.body.3":                  ["Heavy", "胖", "胖", "太め"],
    "cfg.panel.body.4":                  ["Huge", "很胖", "很胖", "かなり太め"],
    "cfg.panel.body.help":               ["The character's build (Slim…Huge). The 3D preview follows as you drag; it is written to this character's save when you press Save settings.",
                                          "角色的胖瘦（瘦…很胖）。拖動時左邊 3D 預覽立刻跟著變；按「儲存設定」才寫進這個角色的存檔。",
                                          "角色的胖瘦（瘦…很胖）。拖动时左边 3D 预览立刻跟着变；按「保存设置」才写进这个角色的存档。",
                                          "キャラクターの体型（細身…かなり太め）。ドラッグ中は左の 3D プレビューが即座に変わり、「設定を保存」でこのキャラクターのセーブに書き込まれます。"],
    "cfg.name.empty":                    ["The name cannot be empty", "名稱不可空白", "名称不可空白", "名前は空にできません"],
    "cfg.name.saved":                    ["Saved — takes effect once you enter the room",
                                          "已儲存，進入房間後生效",
                                          "已保存，进入房间后生效",
                                          "保存しました。ルームに入ると反映されます"],
    "cfg.server_address.label":          ["Server address", "伺服器位址", "服务器地址", "アドレス"],
    "cfg.server_address.help":           ["IP or hostname (e.g. 192.168.1.10 / dance.example.com). ★Empty = offline only; it is used when you press Login.",
                                          "IP 或主機名（例：192.168.1.10 / dance.example.com）。★留空＝純單機，填了按登入才會去連。",
                                          "IP 或主机名（例：192.168.1.10 / dance.example.com）。★留空＝纯单机，填了按登录才会去连。",
                                          "IP またはホスト名（例：192.168.1.10 / dance.example.com）。★空欄＝オフライン専用。入力するとログイン時に接続します。"],
    "cfg.server_port.label":             ["Port", "連線埠", "连接端口", "ポート"],
    "cfg.server_port.help":              ["Server port (1-65535, default 27015). Must match the server's --port.",
                                          "伺服器 port（1~65535，預設 27015）。要與 server 啟動時的 --port 一致。",
                                          "服务器 port（1~65535，默认 27015）。要与 server 启动时的 --port 一致。",
                                          "サーバーのポート（1〜65535、既定 27015）。サーバー起動時の --port と一致させてください。"],
    "cfg.server_password.label":         ["Password", "進站密碼", "进站密码", "パスワード"],
    "cfg.server_password.help":          ["Must match the server's --password. Empty = connect to a server with no password.",
                                          "要與 server 的 --password 一致才連得上。留空＝連到沒設密碼的 server。",
                                          "要与 server 的 --password 一致才连得上。留空＝连到没设密码的 server。",
                                          "サーバーの --password と一致しないと接続できません。空欄＝パスワード無しのサーバー用。"],
    "cfg.server_token.label":            ["Identity token", "身分 token", "身份 token", "認証トークン"],
    "cfg.server_token.help":             ["For public servers: the password is the shared door, the token is how the server knows it is you. Empty = do not send one.",
                                          "公網伺服器用：密碼是大家共用的門，token 是「伺服器認得的你」。留空＝不帶。",
                                          "公网服务器用：密码是大家共用的门，token 是「服务器认得的你」。留空＝不带。",
                                          "公開サーバー用：パスワードは全員共通の入り口、トークンは「サーバーがあなたと分かる印」です。空欄＝送りません。"],
    "cfg.server_tls.label":              ["TLS encryption", "TLS 加密連線", "TLS 加密连接", "TLS 暗号化"],
    "cfg.server_tls.help":               ["★Always on for a public server: without it the password, token and chat all travel in the clear. The server needs --tls-cert.",
                                          "★開在公網一定要開：不開的話密碼、token、聊天內容全是明文。伺服器要有 --tls-cert。",
                                          "★开在公网一定要开：不开的话密码、token、聊天内容全是明文。服务器要有 --tls-cert。",
                                          "★公開サーバーでは必ずオンに：切るとパスワード・トークン・チャットがすべて平文で流れます。サーバー側に --tls-cert が必要です。"],
    "cfg.server_cert_fingerprint.label": ["Cert fingerprint", "憑證指紋", "凭证指纹", "証明書の指紋"],
    "cfg.server_cert_fingerprint.help":  ["SHA-256 (the server prints it on start-up; colons are fine). ★Required for a self-signed certificate, otherwise validation always fails. Empty = normal CA validation.",
                                          "SHA-256（伺服器開機會印出來，冒號可留）。★自簽憑證一定要填，否則驗證必定失敗。留空＝走一般 CA 驗證。",
                                          "SHA-256（服务器开机会印出来，冒号可留）。★自签凭证一定要填，否则验证必定失败。留空＝走一般 CA 验证。",
                                          "SHA-256（サーバー起動時に表示されます。コロンはそのままで可）。★自己署名証明書では必須で、無いと検証は必ず失敗します。空欄＝通常の CA 検証。"],
    "cfg.net_auto_download.label":       ["Auto-download", "缺歌自動下載", "缺歌自动下载", "曲を自動DL"],
    "cfg.net_auto_download.help":        ["Seated players download a missing song from the server automatically (spectators never do).",
                                          "座位玩家缺歌時自動從伺服器下載（旁觀者一律不自動下載）。",
                                          "座位玩家缺歌时自动从服务器下载（旁观者一律不自动下载）。",
                                          "席に着いているプレイヤーは、持っていない曲をサーバーから自動でダウンロードします（観戦者は常に対象外）。"],
    "cfg.net_max_download_mb.label":     ["Download cap", "下載上限 MB", "下载上限 MB", "DL上限 MB"],
    "cfg.net_max_download_mb.help":      ["Size cap per song for auto-download (1-2048 MB). Anything bigger is just reported as missing, so a slow line does not stall you.",
                                          "自動下載的單首歌大小上限（1~2048 MB）。超過就只顯示缺歌，避免在慢速網路上卡很久。",
                                          "自动下载的单首歌大小上限（1~2048 MB）。超过就只显示缺歌，避免在慢速网络上卡很久。",
                                          "自動ダウンロードする 1 曲あたりの上限（1〜2048 MB）。超える曲は「未所持」と表示するだけにして、遅い回線で待たされないようにします。"],
    "cfg.judge_level.label":             ["Judge level", "判定精度", "判定精度", "判定精度"],
    "cfg.judge_level.help":              ["StepMania's timing tiers: higher = stricter. Level 4 = Perfect ±45ms; level 2 is 1.33x wider, level 8 only 0.33x.",
                                          "StepMania 的「精N」：數字越大越嚴格。精4＝Perfect ±45ms；精2 寬 1.33 倍、精8 只剩 0.33 倍。",
                                          "StepMania 的「精N」：数字越大越严格。精4＝Perfect ±45ms；精2 宽 1.33 倍、精8 只剩 0.33 倍。",
                                          "StepMania の判定段階：数字が大きいほど厳しくなります。4＝Perfect ±45ms、2 は 1.33 倍広く、8 は 0.33 倍しかありません。"],
    "cfg.global_offset_ms.label":        ["Judge offset", "判定 offset", "判定 offset", "判定オフセット"],
    "cfg.global_offset_ms.help":         ["Positive = judgement moves later (raise it if you keep hitting early). The machine's audio latency is already compensated; this is personal taste only. Measure it with the editor's F2 tap test.",
                                          "正＝判定時間往後（整體打太早就往正的調）。機器的音訊延遲已自動補掉，這裡只留個人偏好；用編輯器 F2 打拍測試量。",
                                          "正＝判定时间往后（整体打太早就往正的调）。机器的音频延迟已自动补掉，这里只留个人偏好；用编辑器 F2 打拍测试量。",
                                          "プラス＝判定を後ろへずらす（全体的に早押しになるなら＋方向へ）。機器のオーディオ遅延は自動補正済みで、ここは個人の好みだけです。エディタの F2 タップテストで測れます。"],
    "cfg.judge_offset_y.label":          ["Judge line Y", "判定線位移", "判定线位移", "判定ライン位置"],
    "cfg.judge_offset_y.help":           ["Only moves where the hit *looks* like it happens; it does not change judgement timing (that is Judge offset). 0 = dead on the receptor line.",
                                          "只影響「看起來要打在哪」，不影響判定時間（那是判定 offset 的事）。0＝正中受擊線。",
                                          "只影响「看起来要打在哪」，不影响判定时间（那是判定 offset 的事）。0＝正中受击线。",
                                          "「どこで打つように見えるか」だけを変え、判定タイミングは変わりません（それは判定オフセットの役目）。0＝レセプター線のちょうど上。"],
    "cfg.scroll_base_bpm.label":         ["Base BPM", "速度基準 BPM", "速度基准 BPM", "基準BPM"],
    "cfg.scroll_base_bpm.help":          ["Scroll speed = this value x speed step x 1.6 px/s. Raising it speeds up every song at every step (default 130).",
                                          "畫面速度 = 這個值 × 速度檔位 × 1.6 px/s。調大＝所有歌所有檔位一起變快（預設 130）。",
                                          "画面速度 = 这个值 × 速度档位 × 1.6 px/s。调大＝所有歌所有档位一起变快（默认 130）。",
                                          "画面速度＝この値 × 速度段階 × 1.6 px/s。上げるとすべての曲・すべての段階が一緒に速くなります（既定 130）。"],
    "cfg.speed_steps.label":             ["Speed steps", "速度檔位表", "速度档位表", "速度段階"],
    "cfg.speed_steps.help":              ["The speed values the room lets you pick, comma separated (default 1,1.5,2,2.5,3,4,5,6,8).",
                                          "房間裡「速度」可以選的檔位清單，逗號分隔（預設 1,1.5,2,2.5,3,4,5,6,8）。",
                                          "房间里「速度」可以选的档位清单，逗号分隔（默认 1,1.5,2,2.5,3,4,5,6,8）。",
                                          "ルームの「速度」で選べる段階の一覧。カンマ区切り（既定 1,1.5,2,2.5,3,4,5,6,8）。"],
    "cfg.rank_based_formation.label":    ["Rank formation", "依名次調整站位", "依名次调整站位", "順位で立ち位置"],
    "cfg.rank_based_formation.help":     ["In a multiplayer round: on (default, official behaviour) = whoever leads slides to the centre-front slot the camera is anchored on. Off = everyone keeps the room's seat order all round.",
                                          "多人同場時：開（預設，官方行為）＝當下第一名會滑到中央前排（鏡頭錨定的那格）。關＝整場照房間座位順序站，不換位。",
                                          "多人同场时：开（默认，官方行为）＝当下第一名会滑到中央前排（镜头锚定的那格）。关＝整场照房间座位顺序站，不换位。",
                                          "複数人プレイ時：オン（既定・公式挙動）＝その時点の 1 位がカメラの基準になる中央前列へ移動します。オフ＝最後までルームの席順のまま並びます。"],
    "cfg.dance_ignore_miss.label":       ["Dance on miss", "失誤不中斷舞蹈", "失误不中断舞蹈", "ミスで中断しない"],
    "cfg.dance_ignore_miss.help":        ["On = dancing ignores combo, misses and HP entirely. Off (default) = official behaviour, breaking the combo stops the dance.",
                                          "開＝跳舞完全不受 combo/miss/血量影響。關（預設）＝官方玩法，斷 combo 會停舞。",
                                          "开＝跳舞完全不受 combo/miss/血量影响。关（默认）＝官方玩法，断 combo 会停舞。",
                                          "オン＝ダンスがコンボ・ミス・HP の影響を一切受けません。オフ（既定）＝公式どおり、コンボが切れると踊りが止まります。"],
    "cfg.load_external_songs.label":     ["External songs", "載入外部歌曲", "加载外部歌曲", "外部曲を読込"],
    "cfg.load_external_songs.help":      ["Master switch for osu / StepMania / Malody songs. Off = no song-folder scan on start-up, no loading screen, official songs only.",
                                          "osu / StepMania / Malody 歌曲的總開關。關掉＝開機不掃歌資料夾、沒有載入進度畫面，只剩官方歌。",
                                          "osu / StepMania / Malody 歌曲的总开关。关掉＝开机不扫歌文件夹、没有加载进度画面，只剩官方歌。",
                                          "osu / StepMania / Malody 曲の総合スイッチ。オフ＝起動時に曲フォルダを走査せず、ロード画面も出ず、公式曲だけになります。"],
    "cfg.additional_song_folders.label": ["Song folders", "額外歌曲資料夾", "额外歌曲文件夹", "追加曲フォルダ"],
    "cfg.additional_song_folders.help":  ["Absolute paths separated by semicolons (e.g. D:/test;E:/songs). Each one is treated as a Songs root: first level = category, second level = one song each.",
                                          "分號分隔的絕對路徑（例：D:/test;E:/songs）。每個都當一個 Songs 根：第一層＝分類，第二層＝各首歌。",
                                          "分号分隔的绝对路径（例：D:/test;E:/songs）。每个都当一个 Songs 根：第一层＝分类，第二层＝各首歌。",
                                          "セミコロン区切りの絶対パス（例：D:/test;E:/songs）。それぞれが Songs のルート扱いで、1 階層目＝カテゴリ、2 階層目＝各曲です。"],
    "cfg.addon_folder.label":            ["ADDON folder", "外掛(ADDON)目錄", "插件(ADDON)目录", "ADDONフォルダ"],
    "cfg.addon_folder.help":             ["Empty = DATA/ADDON. Give an absolute path to keep a whole add-on pack (SONG/NOTESKIN/THEME/MODEL) on another drive.",
                                          "留空＝DATA/ADDON。想把整包外掛（SONG/NOTESKIN/THEME/MODEL）放別顆硬碟就填絕對路徑。",
                                          "留空＝DATA/ADDON。想把整包插件（SONG/NOTESKIN/THEME/MODEL）放别颗硬盘就填绝对路径。",
                                          "空欄＝DATA/ADDON。アドオン一式（SONG/NOTESKIN/THEME/MODEL）を別のドライブに置きたいときは絶対パスを入れてください。"],
    "cfg.difficulty_calc.label":         ["Difficulty calc", "難度計算方式", "难度计算方式", "難易度計算"],
    "cfg.difficulty_calc.help":          ["Only affects external charts whose difficulty we have to compute (.gn charts always keep their own). Whichever you pick drives the printed number, the random-difficulty ranges and the Easy/Normal/Hard slotting.",
                                          "只影響要自己算難度的外部譜（.gn 一律保留原難度）。選了哪套，顯示數字/隨機難度範圍/簡單普通困難分槽就全照那套。",
                                          "只影响要自己算难度的外部谱（.gn 一律保留原难度）。选了哪套，显示数字/随机难度范围/简单普通困难分槽就全照那套。",
                                          "難易度を自前で計算する必要のある外部譜面にだけ影響します（.gn は常に元の難易度のまま）。選んだ方式が、表示される数値・ランダム難易度の範囲・かんたん/ふつう/むずかしいの振り分けすべてに使われます。"],
    "cfg.difficulty_calc.minacalc":      ["MinaCalc (MSD)", "MinaCalc (MSD)", "MinaCalc (MSD)", "MinaCalc (MSD)"],
    "cfg.difficulty_calc.osu":           ["osu! stars", "osu! 星數", "osu! 星数", "osu! スター"],
    "cfg.song_ui_alpha.label":           ["Browser opacity", "選歌面板透明度", "选歌面板透明度", "選曲パネル濃度"],
    "cfg.song_ui_alpha.help":            ["Overall opacity of the floating category browser behind the song-select 資料夾 tab (0 = invisible, 1 = opaque, default 0.6).",
                                          "選歌畫面「資料夾」那個浮動分類瀏覽面板的整體不透明度（0=全透明、1=不透明，預設 0.6）。",
                                          "选歌画面「文件夹」那个浮动分类浏览面板的整体不透明度（0=全透明、1=不透明，默认 0.6）。",
                                          "選曲画面の「フォルダ」カテゴリ側に浮いているブラウザパネル全体の不透明度（0＝完全に透明、1＝不透明、既定 0.6）。"],
    "cfg.collapse_short_holds.label":    ["Short holds→tap", "極短長條轉單鍵", "极短长条转单键", "短いロング→単押"],
    "cfg.collapse_short_holds.help":     ["Long notes shorter than 83ms become a single tap (head and tail land in the same judgement window = impossible to play). External converted charts only.",
                                          "短於 83ms 的 long note 直接收成單顆 note（頭尾擠在同一個判定窗＝按不出來）。只對外部轉檔譜生效。",
                                          "短于 83ms 的 long note 直接收成单颗 note（头尾挤在同一个判定窗＝按不出来）。只对外部转档谱生效。",
                                          "83ms より短いロングノートを単押しに変換します（始点と終点が同じ判定窓に入る＝押し分けられないため）。外部から変換した譜面にのみ適用されます。"],
    "cfg.combo_text_scale.label":        ["COMBO size", "COMBO 字大小", "COMBO 字大小", "COMBO サイズ"],
    "cfg.combo_text_scale.help":         ["Overall size of the COMBO word plus the streak number (1.0 = official size). Cosmetic only — judgement and score are untouched.",
                                          "COMBO 字樣＋連段數字的整體大小比例（1.0＝官方原尺寸）。純顯示，不影響判定與分數。",
                                          "COMBO 字样＋连段数字的整体大小比例（1.0＝官方原尺寸）。纯显示，不影响判定与分数。",
                                          "COMBO の文字と連段数の全体的な大きさ（1.0＝公式と同じ）。見た目だけで、判定やスコアには影響しません。"],
    "cfg.combo_text_alpha.label":        ["COMBO opacity", "COMBO 字不透明度", "COMBO 字不透明度", "COMBO 不透明度"],
    "cfg.combo_text_alpha.help":         ["The text sits right on the note panel, so keeping it faint stops it covering the falling notes (default 60%). 0 = invisible.",
                                          "字就疊在音符板上，淡一點才不會擋住下落中的音符（預設 60%）。0＝完全看不見。",
                                          "字就叠在音符板上，淡一点才不会挡住下落中的音符（默认 60%）。0＝完全看不见。",
                                          "文字はノーツパネルの上に重なるので、薄めにしておくと落ちてくるノーツを隠しません（既定 60%）。0＝まったく見えません。"],
    "cfg.combo_text_pop.label":          ["COMBO pop", "COMBO 字彈跳", "COMBO 字弹跳", "COMBO 弾み"],
    "cfg.combo_text_pop.help":           ["How far the text springs on a hit at its peak (official 2.0 = doubles then settles back, 1.0 = no bounce at all).",
                                          "打中時彈到最大那一瞬間的倍率（官方 2.0＝彈到兩倍再收回，1.0＝完全不彈跳）。",
                                          "打中时弹到最大那一瞬间的倍率（官方 2.0＝弹到两倍再收回，1.0＝完全不弹跳）。",
                                          "打った瞬間に文字が最大まで弾む倍率（公式は 2.0＝2 倍まで弾んで戻る、1.0＝まったく弾まない）。"],
    "cfg.judge_text_scale.label":        ["Judge size", "判定字大小", "判定字大小", "判定文字サイズ"],
    "cfg.judge_text_scale.help":         ["Overall size of the PERFECT / COOL / BAD / MISS judgement words (1.0 = official size).",
                                          "PERFECT / COOL / BAD / MISS 判定字樣的整體大小比例（1.0＝官方原尺寸）。",
                                          "PERFECT / COOL / BAD / MISS 判定字样的整体大小比例（1.0＝官方原尺寸）。",
                                          "PERFECT / COOL / BAD / MISS の判定文字の全体的な大きさ（1.0＝公式と同じ）。"],
    "cfg.judge_text_alpha.label":        ["Judge opacity", "判定字不透明度", "判定字不透明度", "判定文字の濃度"],
    "cfg.judge_text_alpha.help":         ["Judgement words do not fade out (officially they just vanish), so this is simply how bright they are while shown (default 60%).",
                                          "判定字不會淡出（官方是顯示完直接消失），這個值就是它顯示期間的亮度（預設 60%）。",
                                          "判定字不会淡出（官方是显示完直接消失），这个值就是它显示期间的亮度（默认 60%）。",
                                          "判定文字はフェードアウトしません（公式でも表示後すぐ消えます）。この値は表示中の明るさそのものです（既定 60%）。"],
    "cfg.judge_text_pop.label":          ["Judge pop", "判定字彈跳", "判定字弹跳", "判定文字の弾み"],
    "cfg.judge_text_pop.help":           ["Same as COMBO pop; the judgement text's settle-back speed is hard-coded by the original game (slower), so this only sets the height.",
                                          "同 COMBO 字彈跳，只是判定字收回的速度是官方寫死的（比較慢），這裡只調幅度。",
                                          "同 COMBO 字弹跳，只是判定字收回的速度是官方写死的（比较慢），这里只调幅度。",
                                          "COMBO の弾みと同じです。判定文字が戻る速さは公式で固定（やや遅め）なので、ここでは大きさだけを調整します。"],
    "cfg.ui_scale.label":                ["UI scale", "UI 縮放", "UI 缩放", "UI スケール"],
    "cfg.ui_scale.help":                 ["⚠ Nothing in the game reads this value yet (everything is framed at 800x600 4:3), so changing it does nothing — it is here to match the config file.",
                                          "⚠ 目前遊戲還沒有任何地方讀這個值（畫面一律走 800×600 4:3 取景），改了不會有變化 —— 先留著對齊設定檔。",
                                          "⚠ 目前游戏还没有任何地方读这个值（画面一律走 800×600 4:3 取景），改了不会有变化 —— 先留着对齐配置文件。",
                                          "⚠ 現在この値を読んでいる箇所はまだありません（画面は常に 800×600 4:3 で構成）。変更しても何も起きません —— 設定ファイルと揃えるために置いてあります。"],
    "cfg.mmd_model.label":               ["Model", "使用模型", "使用模型", "使用モデル"],
    "cfg.mmd_model.help":                ["★Picking one *is* the switch — there is no separate on/off. The first entry \"{0}\" keeps the original SDO character. Drop a whole MMD model folder (the .pmx plus its textures) into DATA/MODEL/ — assets/MODEL/ in the dev tree; one folder = one model and it shows up here.",
                                          "★選了就是要用它 —— 沒有另外的總開關。第一個選項「{0}」＝維持 SDO 原角色。把整個 MMD 模型資料夾（含 .pmx 與它的貼圖）放進 DATA/MODEL/，開發樹是 assets/MODEL/；一個資料夾＝一個模型，這裡就會出現。",
                                          "★选了就是要用它 —— 没有另外的总开关。第一个选项「{0}」＝维持 SDO 原角色。把整个 MMD 模型文件夹（含 .pmx 与它的贴图）放进 DATA/MODEL/，开发树是 assets/MODEL/；一个文件夹＝一个模型，这里就会出现。",
                                          "★選ぶこと自体がスイッチです —— 別にオン/オフはありません。先頭の「{0}」＝SDO 本来のキャラのまま。MMD モデルのフォルダ（.pmx とそのテクスチャ一式）を DATA/MODEL/ に置いてください（開発ツリーでは assets/MODEL/）。1 フォルダ＝1 モデルとしてここに出てきます。"],
    "cfg.mmd_model.auto_first":          ["(auto: the first one)", "(自動：第一個)", "(自动：第一个)", "(自動：最初の1つ)"],
    "cfg.mmd_model.not_found":           ["{0} (not found)", "{0}(找不到)", "{0}(找不到)", "{0}(見つかりません)"],
    "cfg.mmd_show_others.label":         ["Show others", "顯示他人模型", "显示他人模型", "他人のモデル"],
    "cfg.mmd_show_others.help":          ["On (default) = you see other people in the room wearing their MMD model (downloaded from the server if you do not have it). Off = everyone shows in their SDO outfit and nothing is downloaded. ★Independent of Model above: you can stay SDO and still see other people's MMD, or the other way round.",
                                          "開(預設)＝同房的人穿 MMD 模型時，你也看得到（本機沒有就自動跟伺服器下載）。關＝別人一律照他的 SDO 穿搭顯示，而且完全不下載。★這與上面「使用模型」互相獨立：可以自己維持 SDO 角色卻看得到別人的 MMD，也可以反過來。",
                                          "开(默认)＝同房的人穿 MMD 模型时，你也看得到（本机没有就自动跟服务器下载）。关＝别人一律照他的 SDO 穿搭显示，而且完全不下载。★这与上面「使用模型」互相独立：可以自己维持 SDO 角色却看得到别人的 MMD，也可以反过来。",
                                          "オン（既定）＝同じルームの人が MMD モデルを使っていれば、あなたにも見えます（手元に無ければサーバーから自動ダウンロード）。オフ＝全員 SDO の服装で表示し、ダウンロードも一切しません。★上の「使用モデル」とは独立です：自分は SDO のままで他人の MMD だけ見ることも、その逆もできます。"],
    "cfg.mmd_share_model.label":         ["Share model", "分享模型", "分享模型", "モデル共有"],
    "cfg.mmd_share_model.help":          ["On (default) = your model is uploaded to the server so the room can see your MMD. Off = they see your SDO outfit instead (your own screen still shows the MMD). ★Many MMD models are licensed against redistribution — that is what this switch is for.",
                                          "開(預設)＝把你的模型上傳給伺服器,同房的人也看得到你的 MMD。關＝別人看到的是你的 SDO 穿搭(你自己畫面上仍然是 MMD)。★很多 MMD 模型的使用規約禁止再配布,這個開關就是為此存在的。",
                                          "开(默认)＝把你的模型上传给服务器,同房的人也看得到你的 MMD。关＝别人看到的是你的 SDO 穿搭(你自己画面上仍然是 MMD)。★很多 MMD 模型的使用规约禁止再配布,这个开关就是为此存在的。",
                                          "オン（既定）＝自分のモデルをサーバーへアップロードし、同じルームの人にも MMD が見えます。オフ＝他人には SDO の服装で見えます（自分の画面は MMD のまま）。★多くの MMD モデルは再配布を規約で禁じています。このスイッチはそのためにあります。"],
    "cfg.mmd_physics.label":             ["Cloth physics", "布料物理模擬", "布料物理模拟", "布の物理"],
    "cfg.mmd_physics.help":              ["Cloth simulation (hair / skirts / ties). ★Turn this off if loading into a stage feels slow — solving cloth is the most expensive part of building an MMD character.",
                                          "布料模擬（頭髮/裙擺/領帶）。★嫌換場景進遊戲慢就關這個 —— 布料求解是建一隻 MMD 角色最貴的一段。",
                                          "布料模拟（头发/裙摆/领带）。★嫌换场景进游戏慢就关这个 —— 布料求解是建一只 MMD 角色最贵的一段。",
                                          "布のシミュレーション（髪・スカート・ネクタイなど）。★ステージ読み込みが遅いと感じたらこれを切ってください —— MMD キャラの生成で最も重いのが布の計算です。"],
    "cfg.mmd_gravity.label":             ["Cloth gravity", "布料重力", "布料重力", "布の重力"],
    "cfg.mmd_gravity.help":              ["Gravity multiplier on the cloth. High = hair and skirts hang lower and swing heavier; low = floaty. The model folder's physics.ini applies first, then this multiplies on top.",
                                          "布料受到的重力倍率。大＝頭髮裙擺被拉得更垂、甩動更沉；小＝飄。模型資料夾裡的 physics.ini 先套，這個值再乘上去。",
                                          "布料受到的重力倍率。大＝头发裙摆被拉得更垂、甩动更沉；小＝飘。模型文件夹里的 physics.ini 先套，这个值再乘上去。",
                                          "布にかかる重力の倍率。大きい＝髪やスカートがより垂れ、揺れも重くなります。小さい＝ふわりと浮きます。まずモデルフォルダの physics.ini が適用され、その上にこの倍率が掛かります。"],
    "cfg.mmd_stiffness.label":           ["Cloth stiffness", "布料剛性", "布料刚性", "布の剛性"],
    "cfg.mmd_stiffness.help":            ["How hard the cloth springs back to its authored shape. Low = limp and pulled straight by gravity; high = stiff and barely moves (twintails the author locked down are already near the stiff end).",
                                          "回彈到原本造型的力道。低＝軟趴趴被重力拉直；高＝硬挺、甩不太動（雙馬尾那種被作者鎖死的部位本來就接近硬的）。",
                                          "回弹到原本造型的力道。低＝软趴趴被重力拉直；高＝硬挺、甩不太动（双马尾那种被作者锁死的部位本来就接近硬的）。",
                                          "元の造形へ戻ろうとする強さ。低い＝だらりと重力で伸びます。高い＝硬くてほとんど揺れません（作者が固めているツインテールなどは元から硬めです）。"],
    "cfg.mmd_collider_scale.label":      ["Collider radius", "碰撞體半徑", "碰撞体半径", "コライダー半径"],
    "cfg.mmd_collider_scale.help":       ["Radius multiplier of the body colliders the cloth hits. Too small = the skirt goes through the legs; too large = the skirt gets pushed out.",
                                          "布料撞身體用的碰撞體半徑倍率。太小＝裙子穿過腿；太大＝裙子被撐飛。",
                                          "布料撞身体用的碰撞体半径倍率。太小＝裙子穿过腿；太大＝裙子被撑飞。",
                                          "布が当たる身体コライダーの半径倍率。小さすぎるとスカートが脚を突き抜け、大きすぎるとスカートが押し広げられます。"],
    "cfg.mmd_profile.label":             ["Physics profile", "物理設定檔", "物理配置文件", "物理プロファイル"],
    "cfg.mmd_profile.help":              ["Save = write the physics currently running (converted values x the sliders above) into the model folder's physics.ini; from then on that model runs from it and other models are unaffected. Reset = delete that file and go back to the values converted straight from the .pmx. The right-hand text says which one is in use.",
                                          "「存檔」＝把現在跑的物理數值(轉換值 × 上面那幾根滑桿)寫成模型資料夾裡的 physics.ini,之後這個模型就照它跑,換別的模型不受影響。「還原」＝刪掉那個檔,回到直接從 .pmx 轉換的值。右邊顯示現在用的是哪一種。",
                                          "「存档」＝把现在跑的物理数值(转换值 × 上面那几根滑杆)写成模型文件夹里的 physics.ini,之后这个模型就照它跑,换别的模型不受影响。「还原」＝删掉那个文件,回到直接从 .pmx 转换的值。右边显示现在用的是哪一种。",
                                          "「保存」＝いま動いている物理値（変換値 × 上のスライダー）をモデルフォルダの physics.ini に書き出します。以後そのモデルはそれに従い、他のモデルには影響しません。「戻す」＝そのファイルを削除し、.pmx から直接変換した値に戻します。右側に現在どちらを使っているか表示されます。"],
    "cfg.mmd_profile.save":              ["Save", "存檔", "存档", "保存"],
    "cfg.mmd_profile.reset":             ["Reset", "還原", "还原", "戻す"],
    "cfg.mmd_scale.label":               ["Model scale", "模型縮放", "模型缩放", "モデル拡縮"],
    "cfg.mmd_scale.help":                ["1 = auto-fit the model to the same height as an SDO dancer (raw model sizes vary wildly, hence auto by default). Multiply here if a model still looks too big or too small.",
                                          "1＝自動把模型縮放到跟 SDO 舞者一樣高（每個模型的原始尺寸差很多，所以預設是自動對齊）。覺得這個模型看起來偏大/偏小就在這裡乘上去。",
                                          "1＝自动把模型缩放到跟 SDO 舞者一样高（每个模型的原始尺寸差很多，所以默认是自动对齐）。觉得这个模型看起来偏大/偏小就在这里乘上去。",
                                          "1＝モデルを SDO のダンサーと同じ身長へ自動で合わせます（素のサイズはモデルごとに大きく違うため、既定は自動）。それでも大きい/小さいと感じたらここで倍率を掛けてください。"],
    "cfg.mmd_lil_toon.label":            ["lilToon shading", "lilToon 著色", "lilToon 着色", "lilToon 描画"],
    "cfg.mmd_lil_toon.help":             ["On = lilToon shading: real lighting, rim light, and an outline that takes colour from the shading. Off (default) = MMD's own look (unlit, the model's toon ramp applied as-is, flat pencil outline). ★This swaps the whole shading stack, it is not an added effect — toggling rebuilds the body. ★lilToon needs light, so turning it on adds a directional light (everything else is unlit and unaffected).",
                                          "開＝用 lilToon 著色：有光照、邊緣光、描邊會跟著明暗變色。關(預設)＝照 MMD 原本的畫法（unlit、模型自帶的 toon ramp 直接貼、純色鉛筆描邊）。★這是換一整套著色，不是加效果 —— 開/關會重建身體。★注意 lilToon 吃光照，開了會自動補一顆平行光（其它東西全是 unlit，不受影響）。",
                                          "开＝用 lilToon 着色：有光照、边缘光、描边会跟着明暗变色。关(默认)＝照 MMD 原本的画法（unlit、模型自带的 toon ramp 直接贴、纯色铅笔描边）。★这是换一整套着色，不是加效果 —— 开/关会重建身体。★注意 lilToon 吃光照，开了会自动补一颗平行光（其它东西全是 unlit，不受影响）。",
                                          "オン＝lilToon で描画します：ライティングあり、リムライトあり、輪郭線も明暗に応じて色が変わります。オフ（既定）＝MMD 本来の描き方（unlit、モデル同梱の toon ランプをそのまま使用、単色の鉛筆線）。★これは描画系一式の入れ替えであり、効果の追加ではありません —— 切り替えると身体を作り直します。★lilToon はライトを必要とするため、オンにすると平行光を 1 つ追加します（他はすべて unlit なので影響なし）。"],
    "cfg.mmd_toon.label":                ["Cel shading", "卡通陰影", "卡通阴影", "トゥーン影"],
    "cfg.mmd_toon.help":                 ["Two-step cel shading (with lilToon on, this is its cel shadow threshold). Off (default) = flat lighting; stage lights otherwise cut a very hard line across the face, which is why it is off by default.",
                                          "明暗只分兩段的卡通上色（開著 lilToon 時＝它的 cel 陰影分界）。關(預設)＝平光；舞台燈光會在臉上切出很硬的一條分界，所以預設不開。",
                                          "明暗只分两段的卡通上色（开着 lilToon 时＝它的 cel 阴影分界）。关(默认)＝平光；舞台灯光会在脸上切出很硬的一条分界，所以默认不开。",
                                          "明暗を 2 段階だけにするトゥーン塗り（lilToon がオンのときは、その cel 影の境目になります）。オフ（既定）＝フラットな明るさ。ステージ照明が顔にくっきりした境目を作ってしまうため、既定ではオフです。"],
    "cfg.mmd_outline.label":             ["Outline", "輪廓描邊", "轮廓描边", "輪郭線"],
    "cfg.mmd_outline.help":              ["The model's own pencil outline (edge). Off = no black line.",
                                          "模型自帶的鉛筆描邊（edge）。關＝沒有黑邊。",
                                          "模型自带的铅笔描边（edge）。关＝没有黑边。",
                                          "モデルが持っている鉛筆線（edge）。オフ＝黒い輪郭は出ません。"],
    "cfg.judge_level.value":             ["Judge {0}", "精{0}", "精{0}", "判定{0}"],
    "cfg.judge_level.justice":           ["JUSTICE", "JUSTICE", "JUSTICE", "JUSTICE"],
    "cfg.mmd_profile.saved":             ["Physics saved to {0} (this model only)",
                                          "物理已存成 {0}（這個模型專屬）",
                                          "物理已存成 {0}（这个模型专属）",
                                          "物理を {0} に保存しました（このモデル専用）"],
    "cfg.mmd_profile.save_failed":       ["Could not save", "存檔失敗", "存档失败", "保存に失敗しました"],
    "cfg.mmd_profile.deleted":           ["physics.ini deleted — back to the .pmx conversion",
                                          "已刪掉 physics.ini → 回到 .pmx 轉換值",
                                          "已删掉 physics.ini → 回到 .pmx 转换值",
                                          "physics.ini を削除しました → .pmx の変換値に戻ります"],
    "cfg.mmd_profile.nothing_to_delete": ["There was no saved profile (the conversion is what is running)",
                                          "本來就沒有存檔（現在跑的就是轉換值）",
                                          "本来就没有存档（现在跑的就是转换值）",
                                          "もともと保存はありません（いま動いているのが変換値です）"],
    "cfg.mmd_profile.state_file":        ["physics.ini", "physics.ini", "physics.ini", "physics.ini"],
    "cfg.mmd_profile.state_unapplied":   ["physics.ini (not applied)",
                                          "physics.ini (未套用)",
                                          "physics.ini (未套用)",
                                          "physics.ini (未適用)"],
    "cfg.mmd_profile.state_converted":   ["converted", "轉換值", "转换值", "変換値"],
}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(here, "..", "65", "My project", "Assets", "StreamingAssets", "Localization")
    out_dir = os.path.normpath(out_dir)
    os.makedirs(out_dir, exist_ok=True)
    for li, (code, name, culture) in enumerate(LANGS):
        idx = ORDER.index(code)
        entries = [{"k": k, "v": STR[k][idx]} for k in STR]
        doc = {"language": code, "name": name, "culture": culture, "entries": entries}
        path = os.path.join(out_dir, code + ".json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=1)
            f.write("\n")
        print(f"wrote {path}  ({len(entries)} keys)")


if __name__ == "__main__":
    main()
